<div id="container">
        <div class=" fix">
                <div id="main">
                        <div class="crumb"><a href="<?php echo LANGPATH; ?>/" class="home">Home</a>&gt;<span class="current">Terms &amp; Conditions</span></div>
                        <div class="help">
                                <h3><span><a>Terms &amp; Conditions</a></span></h3>
                                <div>
                                        <p>When you visit ukhollister.co.uk.  or send an email to us, you are communicating with us in electronic way, which means that you agree to accept our electronic messages. We may contact you by email or issue notifications on ukhollister.co.uk.  Can it prove that it has sent you the electronic messages or issued the notices on our website, it would be deemed that you have received all the agreement, declaration, proclamation and other information? </p>
                                        <h4>Copyright</h4>
                                        <p>All the information posted on ukhollister.co.uk.  such as statement, diagram, sign, button icon, image, audio document segments, digital download, data edit and software belong to the property of our company or our partners, under the protection of China and International Copyright Law. The compilation of all the information on our website is the exclusive property of ukhollister.co.uk. , under the protection of Canada and International Copyright Law. All the software deployed belongs to the property of our company under the protection of China and International Copyright Law.</p>
                                        <h4>Admission and website entry</h4>
                                        <p>ukhollister.co.uk.  grants individual to enter and use its website. Without the written consent of it, any form of download (except page temporary documents) or modification to our website or any part of it are strictly forbidden. This admission does not include the resale or commercial utilization of ukhollister.co.uk. or its content, any collection and utilization of catalogue, instruction and price table, any derivative utilization, any download or copy of the account information for commercial purposes, or the employment of robots or any other alike tools for collecting and extracting data. Without the inerrant written consent we strictly prohibit systematically obtaining the content of ukhollister.co.uk. to directly or indirectly establish or edit corpus, compilation, database or directory inquiries (regardless of the use of automatic instrument or manual operation) Besides, we strictly prohibit employing the content and materials of ukhollister.co.uk. for the purpose not permitted by this conditions of use. Without the inerrant written consent anyone should not copy, replicate, imitate, sell, resale, visit or utilize by any other means ukhollister.co.uk. or any part of it for whatever commercial purposes. Without the inerrant written consent the appropriation of the trade mark, signs or other proprietary information (including image, statement, website design or pattern) of ukhollister.co.uk.  or its affiliated companies by using frame or its functions is not allowed. Without the inerrant written consent you should not borrow our company name and trade mark through Meta Tags or any other means of “hidden text”. Any unauthorized utilization will end the permission or approval by ukhollister.co.uk. . You are granted with limited, revocable and non-exclusive right to build hyperlink to ukhollister.co.uk. Home only when this link does not describe the products and services of us in fake, misleading, depreciating or other invasive ways. Without the inerrant written consent you are forbidden from using any signs or other proprietary icons or trade mark as part of this link.</p>
                                        <h4>Your account</h4>
                                        <p>If you decide to use our website, you are responsible for keeping secrete of your account information and password and restricting the entry to your computer and you also approve to respond all the activities with your account and password. We do not sell products to children. If you have not reach the age of 18, you are not allowed to perform any transactions on our website unless under the supervision of your parents or guardians and within the scope of relevant international laws.</p>
                                        <h4>Comments, utterance, message and other statement</h4>
                                        <p>Visitors are allowed to post comments, utterance and other statement as well as to table proposals, ideas, suggestions, problems or other information as long as the content does not include illegal messages, advertisements, threats, infringes on the privacy of others, violate intellectual property rights or hurt or aggress any third party or cause disgust to the public. You are also prohibited from the spreading software virus, political propaganda, commercial canvass, chain letter, massive emails or other forms of “junk mail”. You should not offer a fake email address, pretend to be others or entities or misadvise the source of card or other information in other ways. Our company holds the rights of deleting or editing these contents (instead of obligation). If you indeed post the messages or submit the materials and unless we receive an objection from the rightful owner of such messages or materials, you award ukhollister.co.uk.  the non-exclusive, free, everlasting, irrevocable and completely re-licensing rights to employ, replicate, modify, adapt, publish, translate, create derivative works, distribute and display this content by any media throughout the world. You also award ukhollister.co.uk. the rights to use the name you provided along with this content. You declare and assure that you have the rights to control the posted content in other manner, its content is accurate, and you declare and assure that you will compensate for the damage to ukhollister.co.uk. brought by the content you provide. ukhollister.co.uk. has the rights (but not obligation) to censor and edit or delete any activities or content. We are not responsible for the submission of messages from you or any third parties.</p>
                                        <h4>Copyright complaints</h4>
                                        <h5>Remedies</h5>
                                        <p>You agree that ukhollister.co.uk. remedy at law for any actual or threatened breach of this Agreement would be inadequate and that ukhollister.co.uk. shall be entitled to specific performance or injunctive relief, or both, in addition to any damages that ukhollister.co.uk. may be legally entitled to recover, together with reasonable expenses of any form of dispute resolution, including, without limitation, attorneys' fees. No right or remedy of ukhollister.co.uk. shall be exclusive of any other, whether at law or in equity, including without limitation damages injunctive relief, attorneys' fees and expenses. No instance of waiver by ukhollister.co.uk.  of its rights or remedies under these terms and conditions shall imply any obligation to grant any similar, future or other waiver.</p>
                                </div>
                        </div>
                </div>
                <?php echo View::factory(LANGPATH . '/doc/left'); ?>
        </div>
</div>