<?php echo View::factory('admin/manage/left')->render(); ?>
<div id="do_right">
    <div class="box">
        <h3>Celebrities</h3>
        <table>
            <tr>
                <td>#</td>
                <td>1</td>
            </tr>
            <tr>
                <td>姓名</td>
                <td>Vincent</td>
            </tr>
            <tr>
                <td>联系方式</td>
                <td>wang.chong@cofreeonline.com</td>
            </tr>
            <tr>
                <td>所在地</td>
                <td>瑞士</td>
            </tr>
            <tr>
                <td>性别</td>
                <td>男</td>
            </tr>
            <tr>
                <td>年龄</td>
                <td>25</td>
            </tr>
            <tr>
                <td>个人博客</td>
                <td>www.vincent.me</td>
            </tr>
            <tr>
                <td>博客ALEXA排名</td>
                <td>11000</td>
            </tr>
            <tr>
                <td>Lookbook地址</td>
                <td>vincent.lookbook.com</td>
            </tr>
            <tr>
                <td>Lookbook粉丝数</td>
                <td>2000</td>
            </tr>
            <tr>
                <td>Facebook地址</td>
                <td>vincent.facebook.com</td>
            </tr>
            <tr>
                <td>Facebook粉丝数</td>
                <td>2000</td>
            </tr>
            <tr>
                <td>其他平台地址</td>
                <td>vincent.other.com</td>
            </tr>
            <tr>
                <td>其他平台数据</td>
                <td>2000</td>
            </tr>
            <tr>
                <td>红人等级</td>
                <td>3</td>
            </tr>
            <tr>
                <td>积分数</td>
                <td>20000</td>
            </tr>
            <tr>
                <td>流量总计</td>
                <td>30000 IP</td>
            </tr>
        </table>
    </div>
</div>
</div>