<?php

defined('SYSPATH') OR die('No direct access allowed.');
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
return array(
    'states' => array(
        'US' => array(
            'U.S. States' => array(
                'AL'             => 'Alabama',
                'AK'             => 'Alaska',
                'AZ'             => 'Arizona',
                'AR'             => 'Arkansas',
                'CA'             => 'California',
                'CO'             => 'Colorado',
                'CT'             => 'Connecticut',
                'DE'             => 'Delaware',
                'DC'             => 'District of Columbia',
                'FL'             => 'Florida',
                'GA'             => 'Georgia',
                'HI'             => 'Hawaii',
                'ID'             => 'Idaho',
                'IL'             => 'Illinois',
                'IN'             => 'Indiana',
                'IA'             => 'Iowa',
                'KS'             => 'Kansas',
                'KY'             => 'Kentucky',
                'LA'             => 'Louisiana',
                'ME'             => 'Maine',
                'MD'             => 'Maryland',
                'MA'             => 'Massachusetts',
                'MI'             => 'Michigan',
                'MN'             => 'Minnesota',
                'MS'             => 'Mississippi',
                'MO'             => 'Missouri',
                'MT'             => 'Montana',
                'NE'             => 'Nebraska',
                'NV'             => 'Nevada',
                'NH'             => 'New Hampshire',
                'NJ'             => 'New Jersey',
                'NM'             => 'New Mexico',
                'NY'             => 'New York',
                'NC'             => 'North Carolina',
                'ND'             => 'North Dakota',
                'OH'             => 'Ohio',
                'OK'             => 'Oklahoma',
                'OR'             => 'Oregon',
                'PA'             => 'Pennsylvania',
                'RI'             => 'Rhode island',
                'SC'             => 'South Carolina',
                'SD'             => 'South Dakota',
                'TN'             => 'Tennessee',
                'TX'             => 'Texas',
                'UT'             => 'Utah',
                'VT'             => 'Vermont',
                'VA'             => 'Virginia',
                'WA'             => 'Washington',
                'WV'             => 'West Virginia',
                'WI'             => 'Wisconsin',
                'WY'             => 'Wyoming'
            ),
            'US Territories' => array(
                'GU'      => 'Guam',
                'PR'      => 'Puerto Rico',
                'VI'      => 'U.S. Virgin Islands',
                'AS'      => 'American Samoa',  
                'FM'      => 'Federated States of Micronesia',
                'MH'      => 'Marshall Islands',
                'PW'      => 'Palau',   
            ),
            'APO/FPO' => array(
                'AA'     => 'Armed Forces - Americas',
                'AE'     => 'Armed Forces - Europe',
                'AP'     => 'Armed Forces - Pacific',
            ),
        ),
        'CA' => array(
            'AB'    => 'Alberta',
            'BC'    => 'British Columbia',
            'MB'    => 'Manitoba',
            'NB'    => 'New Brunswick',
            'NL'    => 'Newfoundland and Labrador',
            'NT'    => 'Northwest Territories',
            'NS'    => 'Nova Scotia',
            'NU'    => 'Nunavut',
            'ON'    => 'Ontario',
            'PE'    => 'Prince Edward Island',
            'QC'    => 'Quebec',
            'SK'    => 'Saskatchewan',
            'YT'    => 'Yukon',
        ),
        'ES' => array(
            'La Coruña',
            'Álava',
            'Albacete',
            'Alicante',
            'Almería',
            'Asturias',
            'Ávila',
            'Badajoz',
            'Islas Baleares',
            'Barcelona',
            'Vizcaya',
            'Burgos',
            'Cáceres',
            'Cádiz',
            'Cantabria',
            'Castellón',
            'Ciudad Real',
            'Córdoba',
            'Cuenca',
            'Guipúzcoa',
            'Gerona',
            'Granada',
            'Guadalajara',
            'Huelva',
            'Huesca',
            'Jaén',
            'La Rioja',
            'Las Palmas',
            'León',
            'Lérida',
            'Lugo',
            'Madrid',
            'Málaga',
            'Murcia',
            'Navarra',
            'Orense',
            'Palencia',
            'Pontevedra',
            'Salamanca',
            'Santa Cruz de Tenerife',
            'Segovia',
            'Sevilla',
            'Soria',
            'Tarragona',
            'Teruel',
            'Toledo',
            'Valencia',
            'Valladolid',
            'Zamora',
            'Zaragoza',
        ),
        'FR' => array(
            "Alsace",
            "Aquitaine",
            "Auvergne",
            "Bretagne",
            "Bourgogne",
            "Centre",
            "Champagne-Ardenne",
            "Franche-Comté",
            "Île-de-France",
            "Languedoc-Roussillon",
            "Limousin",
            "Lorraine",
            "Basse-Normandie",
            "Midi-Pyrénées",
            "Nord-Pas-de-Calais",
            "Pays de la Loire",
            "Picardie",
            "Poitou-Charentes",
            "Provence-Alpes-Côte d'Azur",
            "Rhône-Alpes",
            "Haute-Normandie",
            "Corse",
            "Guyane",
            "Guadeloupe",
            "Martinique",
            "Mayotte",
            "La Réunion",
        ),
        'AU' => array(
            'New South Wales',
            'Queensland',
            'South Australia',
            'Tasmania',
            'Victoria',
            'Western Australia',
            'Australian Capital Territory',
            'Northern Territory'
        ),
        'NO' => array(
            'Østfold',
            'Akershus',
            'Oslo',
            'Hedmark',
            'Oppland',
            'Buskerud',
            'Vestfold',
            'Telemark',
            'Aust-Agder',
            'Vest-Agder',
            'Rogaland',
            'Hordaland',
            'Sogn og Fjordane',
            'Møre og Romsdal',
            'Sør-Trøndelag',
            'Nord-Trøndelag',
            'Nordland',
            'Troms',
            'Finnmark'
        ),
        'DE' => array(
            'Baden-Württemberg',
            'Bayern',
            'Berlin',
            'Brandenburg',
            'Bremen',
            'Hamburg',
            'Hessen',
            'Mecklenburg-Vorpommern',
            'Niedersachsen',
            'Nordrhein-Westfalen',
            'Rheinland-Pfalz',
            'Saarland',
            'Sachsen',
            'Sachsen-Anhalt',
            'Schleswig-Holstein',
            'Thüringen',
        ),
        'PL' => array(
            'Greater Poland',
            'Kuyavian-Pomeranian',
            'Lesser Poland',
            'Łódź',
            'Lower Silesian',
            'Lublin',
            'Lubusz',
            'Masovian',
            'Opole',
            'Podlaskie',
            'Pomeranian',
            'Silesian',
            'Subcarpathian',
            'Świętokrzyskie',
            'Warmian-Masurian',
            'West Pomeranian',
        ),
        'GB' => array(
            'ENGLAND' => array(
                'Avon',
                'Bedfordshire',
                'Berkshire',
                'City of Bristol',
                'Buckinghamshire',
                'Cambridgeshire',
                'Cambridgeshire and Isle of Ely',
                'Cheshire',
                'Cleveland',
                'Cornwall',
                'Cumberland',
                'Cumbria',
                'Derbyshire',
                'Devon',
                'Dorset',
                'Durham',
                'East Suffolk',
                'East Sussex',
                'Essex',
                'Gloucestershire',
                'Greater London',
                'Greater Manchester',
                'Hampshire',
                'Hereford and Worcester',
                'Herefordshire',
                'Hertfordshire',
                'Humberside',
                'Huntingdon and Peterborough',
                'Isle of Ely',
                'Isle of Wight',
                'Kent',
                'Lancashire',
                'Leicestershire',
                'Lincolnshire',
                'London',
                'Merseyside',
                'Middlesex',
                'Norfolk',
                'Northamptonshire',
                'Northumberland',
                'North Humberside',
                'North Yorkshire',
                'Nottinghamshire',
                'Oxfordshire',
                'Soke of Peterborough',
                'Rutland',
                'Shropshire',
                'Somerset',
                'South Humberside',
                'South Yorkshire',
                'Staffordshire',
                'Suffolk',
                'Surrey',
                'Sussex',
                'Tyne and Wear',
                'Warwickshire',
                'West Midlands',
                'Westmorland',
                'West Suffolk',
                'West Sussex',
                'West Yorkshire',
                'Wiltshire',
                'Worcestershire',
                'Yorkshire',
            ),
            'NORTH IRELAND' => array(
                'Antrim',
                'Armagh',
                'Belfast',
                'Down',
                'Fermanagh',
                'Londonderry',
                'Tyrone',
            ),
            'SCOLATLAND' => array(
                'Aberdeen',
                'Aberdeenshire',
                'Angus',
                'Argyll',
                'Ayrshire',
                'Banffshire',
                'Berwickshire',
                'Bute',
                'Caithness',
                'Clackmannanshire',
                'Cromartyshire',
                'Dumfriesshire',
                'Dunbartonshire',
                'Dundee',
                'East Lothian',
                'Edinburgh',
                'Fife',
                'Glasgow',
                'Inverness-shire',
                'Kincardineshire',
                'Kinross-shire',
                'Kirkcudbrightshire',
                'Lanarkshire',
                'Midlothian',
                'Moray',
                'Nairnshire',
                'Orkney',
                'Peeblesshire',
                'Perthshire',
                'Renfrewshire',
                'Ross and Cromarty',
                'Ross-shire',
                'Roxburghshire',
                'Selkirkshire',
                'Shetland',
                'Stirlingshire',
                'Sutherland',
                'West Lothian',
                'Wigtownshire',
            ),
            'WALSE' => array(
                'Anglesey',
                'Brecknockshire',
                'Caernarfonshire',
                'Cardiganshire',
                'Carmarthenshire',
                'Clwyd',
                'Denbighshire',
                'Dyfed',
                'Flintshire',
                'Glamorgan',
                'Gwent',
                'Gwynedd',
                'Merionethshire',
                'Mid Glamorgan',
                'Monmouthshire',
                'Montgomeryshire',
                'Pembrokeshire',
                'Powys',
                'Radnorshire',
                'South Glamorgan',
                'West Glamorgan',
            )
        ),
        'SE' => array(
            'Stockholm',
            'Västerbotten',
            'Norrbotten',
            'Uppsala',
            'Södermanland',
            'Östergötland',
            'Jönköping',
            'Kronoberg',
            'Kalmar',
            'Gotland',
            'Blekinge',
            'Skåne',
            'Halland',
            'Västra Götaland',
            'Värmland',
            'Örebro',
            'Västmanland',
            'Dalarna County',
            'Gävleborg',
            'Västernorrland',
            'Jämtland',
        ),
        'IT' => array(
            "Agrigento",
            "Alessandria",
            "Ancona",
            "Aosta",
            "Arezzo",
            "Ascoli Piceno",
            "Asti",
            "Avellino",
            "Bari",
            "Barletta Andria Trani",
            "Belluno",
            "Benevento",
            "Bergamo",
            "Biella",
            "Bologna",
            "Bolzano",
            "Brescia",
            "Brindisi",
            "Cagliari",
            "Caltanissetta",
            "Campobasso",
            "Carbonia Iglesias",
            "Caserta",
            "Catania",
            "Catanzaro",
            "Chieti",
            "Città del Vaticano",
            "Como",
            "Cosenza",
            "Cremona",
            "Crotone",
            "Cuneo",
            "Enna",
            "Fermo",
            "Ferrara",
            "Firenze",
            "Foggia",
            "Forlì-Cesena",
            "Frosinone",
            "Genova",
            "Gorizia",
            "Grosseto",
            "Imperia",
            "Isernia",
            "La Spezia",
            "L'Aquila",
            "Latina",
            "Lecce",
            "Lecco",
            "Livorno",
            "Lodi",
            "Lucca",
            "Macerata",
            "Mantova",
            "Massa Carrara",
            "Matera",
            "Medio Campidano",
            "Messina",
            "Milano",
            "Modena",
            "Monza e Brianza",
            "Napoli",
            "Novara",
            "Nuoro",
            "Ogliastra",
            "Olbia Tempio",
            "Oristano",
            "Padova",
            "Palermo",
            "Parma",
            "Pavia",
            "Perugia",
            "Pesaro-Urbino",
            "Pescara",
            "Piacenza",
            "Pisa",
            "Pistoia",
            "Pordenone",
            "Potenza",
            "Prato",
            "Ragusa",
            "Ravenna",
            "Reggio Calabria",
            "Reggio Emilia",
            "Rieti",
            "Rimini",
            "Roma",
            "Rovigo",
            "Salerno",
            "San Marino",
            "Sassari",
            "Savona",
            "Siena",
            "Siracusa",
            "Sondrio",
            "Taranto",
            "Teramo",
            "Terni",
            "Torino",
            "Trapani",
            "Trento",
            "Treviso",
            "Trieste",
            "Udine",
            "Varese",
            "Venezia",
            "Verbania",
            "Verbano Cusio Ossola",
            "Vercelli",
            "Verona",
            "Vibo Valentia",
            "Vicenza",
            "Viterbo",
        ),
        'RU' => array(
            'Адыгея',
            'Башкортостан',
            'Бурятия',
            'Алтай',
            'Дагестан',
            'Ингушетия',
            'Кабардино-Балкарская Республика',
            'Калмыкия',
            'Карачаево-Черкесия',
            'Карелия',
            'Коми',
            'Республика Марий Эл',
            'Мордовия',
            'Саха',
            'Северная Осетия-Алания',
            'Татарстан',
            'Тува',
            'Удмуртская Республика',
            'Хакасия',
            'Чечня',
            'Чувашская АССР',
            'Алтайский Край',
            'Забайкальский Край',
            'Камчатский Край',
            'Краснодарский Край',
            'Красноярский Край',
            'Пермский Край',
            'Приморский Край',
            'Ставропольский Край',
            'Хабаровский Край',
            'Амурская Область',
            'Астраханская Область',
            'Белгородская Область',
            'Брянская Область',
            'Владимирская Область',
            'Волгоградская Область',
            'Вологодская Область',
            'Воронежская Область',
            'Ивановская Область',
            'Иркутская Область',
            'Калининградская Область',
            'Калужская Область',
            'Кемеровская Область',
            'Кировская Область',
            'Костромская Область',
            'Курганская Область',
            'Курская Область',
            'Ленинградская Область',
            'Липецкая Область',
            'Магаданская Область',
            'Московская Область',
            'Мурманская Область',
            'Нижегородская Область',
            'Новгородская Область',
            'Новосибирская Область',
            'Омская Область',
            'Оренбургская Область',
            'Орловская Область',
            'Пензенская Область',
            'Псковская Область',
            'Ростовская Область',
            'Рязанская Область',
            'Самарская Область',
            'Саратовская Область',
            'Сахалинская Область',
            'Свердловская Область',
            'Смоленская Область',
            'Тамбовская Область',
            'Тамбовская Область',
            'Томская Область',
            'Тульская Область',
            'Тюменская Область',
            'Ульяновская Область',
            'Челябинская Область',
            'Ярославля Область',
            'Москва',
            'Санкт-Петербург',
            'Еврейская Автономная Область',
            'Ненецкий Автономный Округ',
            'Ханты-Мансийский Автономный Округ – Югра',
            'Чукотский Автономный Округ',
            'Ямало-Ненецкого Автономного Округа',
            'Архангельская Область',
        ),
        'MX' => array(
            "Distrito Federal",
            "Aguascalientes",
            "Baja California",
            "Baja California Sur",
            "Campeche",
            "Chiapas",
            "Chihuahua",
            "Coahuila de Zaragoza",
            "Colima",
            "Durango",
            "Guanajuato",
            "Guerrero",
            "Hidalgo",
            "Jalisco",
            "México",
            "Michoacán de Ocampo",
            "Morelos",
            "Nayarit",
            "Nuevo León",
            "Oaxaca",
            "Puebla",
            "Querétaro de Arteaga",
            "Quintana Roo",
            "San Luis Potosí",
            "Sinaloa",
            "Sonora",
            "Tabasco",
            "Tamaulipas",
            "Tlaxcala",
            "Veracruz de Ignacio de la Llave",
            "Yucatán",
            "Zacatecas",
        ),
        'CO' => array(
            "Amazonas",
            "Antioquia",
            "Arauca",
            "Atlántico",
            "Bolívar",
            "Boyacá",
            "Caldas",
            "Caquetá",
            "Casanare",
            "Cauca",
            "Cesar",
            "Chocó",
            "Córdoba",
            "Cundinamarca",
            "Guainía",
            "Guaviare",
            "Huila",
            "La Guajira",
            "Magdalena",
            "Meta",
            "Nariño",
            "Norte de Santander",
            "Putumayo",
            "Quindío",
            "Risaralda",
            "San Andrés y Providencia",
            "Santander",
            "Sucre",
            "Tolima",
            "Valle del Cauca",
            "Vaupés",
            "Vichada",
        ),
        'CL' => array(
            "Provincia de Arica",
            "Provincia de Parinacota",
            "Provincia de Iquique",
            "Provincia del Tamarugal",
            "Provincia de Tocopilla",
            "Provincia de El Loa",
            "Provincia de Antofagasta",
            "Provincia de Cha?aral",
            "Provincia de Copiapó",
            "Provincia de Huasco",
            "Provincia de Elqui",
            "Provincia de Limarí",
            "Provincia de Choapa",
            "Provincia de Petorca",
            "Provincia de Los Andes",
            "Provincia de San Felipe de Aconcagua",
            "Provincia de Quillota",
            "Provincia de Valparaíso",
            "Provincia de San Antonio",
            "Provincia de Isla de Pascua",
            "Provincia de Marga Marga",
            "Provincia de Chacabuco",
            "Provincia de Santiago",
            "Provincia de Cordillera",
            "Provincia de Maipo",
            "Provincia de Melipilla",
            "Provincia de Talagante",
            "Provincia de Cachapoal",
            "Provincia de Colchagua",
            "Provincia de Cardenal Caro",
            "Provincia de Curicó",
            "Provincia de Talca",
            "Provincia de Linares",
            "Provincia de Cauquenes",
            "Provincia de Ñuble",
            "Provincia de Biobío",
            "Provincia de Concepción",
            "Provincia de Arauco",
            "Provincia de Malleco",
            "Provincia de Cautín",
            "Provincia de Valdivia",
            "Provincia del Ranco",
            "Provincia de Osorno",
            "Provincia de Llanquihue",
            "Provincia de Chiloé",
            "Provincia de Palena",
            "Provincia de Coyhaique",
            "Provincia de Aysén",
            "Provincia de General Carrera",
            "Provincia de Capitán Prat",
            "Provincia de Última Esperanza",
            "Provincia de Magallanes",
            "Provincia de Tierra del Fuego",
            "Provincia de la Antártica Chilena",
        ),
    ),
    'called' => array(
        'US' => 'State',
        'GB' => 'County',
        'UA' => 'Oblast',
        'PT' => 'District',
        'GR' => 'Region',
        'BR' => 'State',
        'NL' => 'Province',
        'CH' => 'Canton',
        'CZ' => 'Region',
        'BE' => 'Province',
        'TR' => 'Province',
        'Default' => 'County / Province',
    )
);
?>