
		<section id="main">
			<!-- crumbs -->
			<div class="container">
				<div class="crumbs">
					<div>
						<a href="<?php echo LANGPATH; ?>/">home</a>
						<a href="<?php echo LANGPATH; ?>/mobile-left" class="visible-xs-inline hidden-sm hidden-md hidden-lg"> > Centro De Ayuda</a> > Privacy & Security
					</div>
				</div>
			</div>
			<!-- main-middle begin -->
			<div class="container">
				<div class="row">
			<?php echo View::factory(LANGPATH . '/doc/left'); ?>
					<article class="user col-sm-9 col-xs-12">
						<div class="tit">
							<h2>Privacy & Security</h2>
						</div>
						<div class="doc-box">
							<p>On http://www.choies.com (from now on, will be referred as choies.com), visitor privacy is of our serious concern. This privacy policy page describes what kind of personal information may be received and collected by choies.com and how the information
								will be used.</p>
							<h4>Search Engine Ads</h4>
							<p>As many other professional sites, choies.com invest on the internet advertisement. Our advertise partners include bing Ads (Yahoo Ads). In order to maximize online advertising ROI and to find target clients, choies.com applied some tracking codes
								generated by those search engines to record user IPs and page viewing flows.</p>
							<h4>Business Contact Data</h4>
							<p>We collect all the business contact data sent through emails or web forms on choies.com from visitors. The visitor identification and contact related data entered will be kept strictly for choies.com’s internal use. Choies.com will ensure the safety
								and proper usage of those data.</p>
							<h4>Information Usage</h4>
							<p>We will only use your personally identifiable information as described below, unless you have specifically consented to another type of use, either at the time the personally identifiable information is collected from you or through some other
								form of consent from you:</p>
							<p>1.We will use personally identifiable information to complete any orders you have placed.</p>
							<p>2.We will use personally identifiable information to provide you with the specific services that you have requested, such as to reach a retailer.</p>
							<p>3.We will use your personally identifiable information to respond to questions that you send to us.</p>
							<p>4.We will use your personally identifiable information to send you emails from time to time, such as newsletters and notices about our promotions.</p>
							<p>5.We may disclose personally identifiable information as required by law or legal process.</p>
							<p>6.We may disclose personally identifiable information to investigate suspected fraud, harassment or other violations of any law, rule or regulation, or the terms or policies for the Web site.</p>
							<h4>OPT OUT/CORRECTIONS</h4>
							<p>
								Upon your request, we will
								<strong>(a)</strong> correct or update your personal information;
								<strong>(b)</strong> stop sending emails to your email address; and/or
								<strong>(c)</strong> disable your account to prevent any future purchases through that account. You can make these requests by livechat, or emailing your request to choies.com’s Customer Support department at
								<a href="mailto:service@choies.com">service@choies.com</a> . Please do not email your credit card number or other sensitive information.
							</p>
							<p>When you register, you will be given the option to opt-out of subscribing to our regular update service. We will send you e mail alerts for new products, features, enhancements, special offers, contests, events of interest, and one-off marketing
								promotions.</p>
							<p>At all times, we will offer you the opportunity to unsubscribe out of any service or update to which you have subscribed, if you change your mind. Any e-mail we send you will contain an easy automated unsubscribe link so that you can opt-out of
								that subscription. Simply follow the indications in the e-mail.</p>
							<p>[CompanyName] Choies Co., Ltd</p>
							<p>[Address] Third Floor, 207 Regent Street, London, W1B 3HH,United Kingdom</p>
							<p>[Email] service@choies.com</p>
							<p>[Contact Number] 44-2032893088</p>
							<p> </p>
						</div>
					</article>
				</div>
			</div>
		</section>
		<!-- footer begin -->

		<div id="gotop" class="hide">
			<a href="#" class="xs-mobile-top"></a>
		</div>

