<?php

return array(
    'en' => array(
        'title1' => 'home',
        'title2' => 'my account',
        'title3' => 'account setting',
        'title4' => 'Account Setting',
        'Email' => 'Email:',
        'First Name'  => 'First Name:',
        'Last Name'  => 'Last Name:',
        'Country'  => 'Country:',
        'Gender'  => 'Gender:',
        'Female'  => 'Female',
        'Male'  => 'Male',
        'Other'  => 'Other',
        'Birthday'  => 'Birthday:',
    ),
    'es' => array(
        'title1' => 'Página de Inicio',
        'title2' => ' RESUMEN DE CUENTA',
        'title3' => 'Configuración de Cuenta',
        'title4' => 'Configuración de Cuenta',
        'Email' => 'Email:',
        'First Name'  => 'Primer Nombre:',
        'Last Name'  => 'Apellido:',
        'Country'  => 'País:',
        'Gender'  => 'Sexo:',
        'Female'  => 'Mujer',
        'Male'  => 'Hombre',
        'Other'  => 'Otro',
        'Birthday'  => 'Fecha De Nacimiento:',
    ),
    'de' => array(
        'title1' => 'Homepage',
        'title2' => 'KONTOÜBERSICHT',
        'title3' => 'Konto Einstellung',
        'title4' => 'Konto Einstellung',
        'Email' => 'E-Mail:',
        'First Name'  => 'Vorname:',
        'Last Name'  => 'Nachname:',
        'Country'  => 'Land:',
        'Gender'  => 'Geschlecht:',
        'Female'  => 'Frau',
        'Male'  => 'Mann',
        'Other'  => 'Andere',
        'Birthday'  => 'Geburtsdatum:',
    ),
    'fr' => array(
        'title1' => 'Accueil',
        'title2' => 'Mon Compte',
        'title3' => 'Paramètre de compte',
        'title4' => 'Paramètre de compte',
        'Email' => 'É-mail:',
        'First Name'  => 'Prénom:',
        'Last Name'  => 'Nom:',
        'Country'  => 'Pays:',
        'Gender'  => 'Sexe:',
        'Female'  => 'Féminin',
        'Male'  => 'Masculin',
        'Other'  => 'Autre',
        'Birthday'  => 'Anniversaire:',
    ),
);