<?php

return array(
    'en' => array(
        'title1' => 'Register to get
                <span>15%</span> Coupon Code and a welcome gift.',
        'title2' => 'CHOIES Member Sign In',
        'Email address' => 'Email address:',
        'Password' => 'Password:',
        'Remember me' => 'Remember me',
        'Tick to keep login for 14 days' => 'Tick to keep login for 14 days.',
        'Forgot password' => 'Forgot password?',
        'Sign in with Facebook' => 'Sign in with Facebook',
        'CHOIES Member Sign Up' => 'CHOIES Member Sign Up',
        'Confirm Password' => 'Confirm Password:',
        'Sign In' => 'Sign In',
        'Sign Up' => 'Sign Up',
    ),
    'de' => array(
        'title1' => 'Registrieren Sie sich, um einen <span>15%</span> Gutscheincode und ein Willkommensgeschenk zu erhalten.',
        'title2' => 'CHOIES Mitglied Anmelden',
        'Email address' => 'E-mail Adresse:',
        'Password' => 'Passwort:',
        'Remember me' => 'Angemeldet bleiben',
        'Tick to keep login for 14 days' => 'Aktivieren Sie bitte die Option, für 14 Tage angemeldet bleiben.',
        'Forgot password' => 'Passwort vergessen?',
        'Sign in with Facebook' => 'Mit Facebook Anmelden',
        'CHOIES Member Sign Up' => 'CHOIES Mitglied Registrieren',
        'Confirm Password' => 'Passwort Bestätigen:',
        'Sign In' => 'ANMELDEN',
        'Sign Up' => 'REGISTRIEREN',
    ),
    'es' => array(
        'title1' => 'Registrate para obtener un cupón de <span>15%</span> de descuento y un regalo de bienvenido.',
        'title2' => 'Acceso para socios',
        'Email address' => 'Email:',
        'Password' => 'Contraseña:',
        'Remember me' => 'Recordarme',
        'Tick to keep login for 14 days' => 'Haga clic para guardar conexión por 14 días.',
        'Forgot password' => '¿Olvidaste tu contraseña?',
        'Sign in with Facebook' => 'Acceder con Facebook',
        'CHOIES Member Sign Up' => 'Únete a Choies',
        'Confirm Password' => 'Confirmar Contraseña:',
        'Sign In' => 'ACCEDER',
        'Sign Up' => 'REGÍSTRATE',
    ),
    'fr' => array(
        'title1' => " S'inscrire pour obtenir <span>15%</span> code de coupon et un cadeau de bienvenue.",
        'title2' => 'Déjà client CHOIES',
        'Email address' => 'Adresse e-mail:',
        'Password' => 'Mot de passe:',
        'Remember me' => 'Rester connecté',
        'Tick to keep login for 14 days' => 'Cochez pour garder connexion pendant 14 jours.',
        'Forgot password' => 'Mot de passe oublié?',
        'Sign in with Facebook' => 'Connexion avec Facebook',
        'CHOIES Member Sign Up' => 'Nouveau client CHOIES',
        'Confirm Password' => 'Confirm Password:',
        'Sign In' => 'SE CONNECTER',
        'Sign Up' => "S'INSCRIRE",
    ),
);