<?php

return array(
    'en' => array(
        'title1' => 'home',
        'title2' => 'my account',
        'title3' => 'my blog show',
        'title4' => 'My Blog Show',
        'TO SHOW' => 'TO SHOW',
        'SHOWED' => 'SHOWED',
        'How to Complete a Show' => 'How to Complete a Show?',
        '1. Copy the Item Link and Paste it to your Blog Show Picture' => '1. Copy the Item Link and Paste it to your Blog Show Picture.',
        '2. Write your show url in the right column and click "Submit"' => '2. Write your show url in the right column and click "Submit".',
        'Show No' => 'Show No.',
        'Product Info' => 'Product Info.',
        'Show Link' => 'Show Link',
        'Item#' => 'Item# :',
        'Order NO' => 'Order NO.:',
        'Copy Item Link' => 'Copy Item Link',
        'add one more link' => 'add one more link',
        'Submit' => 'Submit',
        'Cancel' => 'Cancel',
        'Edit' => 'Edit',
        'Showed' => 'Showed',

    ),
    'es' => array(
        'title1' => 'Página de Inicio',
        'title2' => 'RESUMEN DE CUENTA',
        'title3' => 'Mi show del blog',
        'title4' => 'Mi show del blog',
        'TO SHOW' => 'PARA MOSTRAR',
        'SHOWED' => 'MOSTRÓ',
        'How to Complete a Show' => '¿Cómo llenar un show?',
        '1. Copy the Item Link and Paste it to your Blog Show Picture' => '1. Copie el Enlace de Artículo y pégalo en tu Blog Mostrar Imagen.',
        '2. Write your show url in the right column and click "Submit"' => '2. Escriba el url de su espectáculo en la columna de la derecha y haga clic en "Enviar".',
        'Show No' => 'Show No.',
        'Product Info' => 'La Información De Producto.',
        'Show Link' => 'Enlace De Show',
        'Item#' => 'artículo# :',
        'Order NO' => 'Pedido NO.:',
        'Copy Item Link' => 'Copiar El Enlace',
        'add one more link' => 'Añadir uno mas enlace',
        'Submit' => 'PRESENTAR',
        'Cancel' => 'Cancelar',
        'Edit' => 'EDITAR',
        'Showed' => 'MOSTRÓ',

    ),
    'de' => array(
        'title1' => 'Homepage',
        'title2' => 'KONTOÜBERSICHT',
        'title3' => 'MEIN BLOG SHOW',
        'title4' => 'MEIN BLOG SHOW',
        'TO SHOW' => 'ZEIGEN',
        'SHOWED' => 'GEZEIGT',
        'How to Complete a Show' => 'Wie man ein Show komplettieren?',
        '1. Copy the Item Link and Paste it to your Blog Show Picture' => '1. Kopieren Sie die Artikel-Link und fügen Sie es zu Ihrem Blog Show Bilder.',
        '2. Write your show url in the right column and click "Submit"' => '2. Schreiben Sie Ihre Show url in der rechten Spalte und klicken Sie auf "Senden".',
        'Show No' => 'Show Nr.',
        'Product Info' => 'Produktinfo.',
        'Show Link' => 'Show Link',
        'Item#' => 'Artikel# :',
        'Order NO' => 'Bestell-Nr:',
        'Copy Item Link' => 'Artikel kopieren Link',
        'add one more link' => 'eine weitere Link hinzufügen',
        'Submit' => 'Senden',
        'Cancel' => 'ABBRECHEN',
        'Edit' => 'EDITIEREN',
        'Showed' => 'Showed',

    ),
    'fr' => array(
        'title1' => 'Accueil',
        'title2' => 'Mon Compte',
        'title3' => 'MON BLOG SHOW',
        'title4' => 'MON BLOG SHOW',
        'TO SHOW' => 'POUR MONTRER',
        'SHOWED' => 'MONTRÉ',
        'How to Complete a Show' => 'Comment remplir un show?',
        '1. Copy the Item Link and Paste it to your Blog Show Picture' => "1. Copiez le lien de l'article et collez-le dans dans votre blog.",
        '2. Write your show url in the right column and click "Submit"' => '2. Rédigez votre show url dans la colonne de droite et cliquez sur « Soumettre ».',
        'Show No' => 'N°de Show',
        'Product Info' => 'Info Produits',
        'Show Link' => 'Lien de Show',
        'Item#' => 'Article# :',
        'Order NO' => 'N°de Commande:',
        'Copy Item Link' => 'Copier le lien d’article',
        'add one more link' => 'ajoutez un nouveau lien',
        'Submit' => 'SOUMETTRE',
        'Cancel' => 'annuler',
        'Edit' => 'RÉDIGER',
        'Showed' => 'MONTRÉ',

    ),
);