<?php

return array(
    'en' => array(
        'title1' => 'home',
        'title2' => 'my account',
        'title3' => 'my coupons',
        'title4' => 'My Coupons',
        'Unused Coupons' => 'Unused Coupons',
        'Coupon Used' => 'Coupon Used',
        'Coupon Code' => 'Coupon Code',
        'Coupon Type' => 'Coupon Type',
        'Coupon Value' => 'Coupon Value',
        'Terms & Conditions' => 'Terms & Conditions',
        'Valid From' => 'Valid From',
        'Expiration Date' => 'Expiration Date',
        'Created Date' => 'Created Date',
        'Order Number' => 'Order Numbe',
        'Saving' => 'Saving',
        'Used Date' => 'Used Date',
        'conditions1' => 'Any items with full price',
        'conditions2' => 'Any items',
    ),
    'es' => array(
        'title1' => 'Página de Inicio',
        'title2' => 'RESUMEN DE CUENTA',
        'title3' => 'Mis Cupones',
        'title4' => 'Mis Cupones',
        'Unused Coupons' => 'Cupónes No Usados',
        'Coupon Used' => 'Cupónes Usados',
        'Coupon Code' => 'Código De Descuento',
        'Coupon Type' => 'Cupón Tipo',
        'Coupon Value' => 'Valor De Cupón',
        'Terms & Conditions' => 'Términos Y Condiciones',
        'Valid From' => 'Validez Desde',
        'Expiration Date' => 'Fecha De Vencimiento',
        'Created Date' => 'Fecha De Creación',
        'Order Number' => 'Numero de pedido',
        'Saving' => 'Ahorro',
        'Used Date' => 'Fecha Usado',
        'conditions1' => 'Cualquier artículo con el precio completo',
        'conditions2' => 'Cualquier artículo',
    ),
    'de' => array(
        'title1' => 'Homepage',
        'title2' => 'KONTOÜBERSICHT',
        'title3' => 'Meine Gutscheine',
        'title4' => 'Meine Gutscheine',
        'Unused Coupons' => 'Unbenutzte Gutscheine',
        'Coupon Used' => 'Verwendete Gutscheine',
        'Coupon Code' => 'Gutschein Code',
        'Coupon Type' => 'Gutschein Typ',
        'Coupon Value' => 'Gutschein Wert',
        'Terms & Conditions' => 'Allgemeine Geschäftsbedingungen',
        'Valid From' => 'Gültig ab',
        'Expiration Date' => 'Ablaufdatum',
        'Created Date' => 'Erstellungsdatum',
        'Order Number' => 'Bestellnummer',
        'Saving' => 'Einsparung',
        'Used Date' => 'Verwendete Daten',
        'conditions1' => 'Alle Artikel mit vollem Preis',
        'conditions2' => 'Alle Artikel',
    ),
    'fr' => array(
        'title1' => 'Accueil',
        'title2' => 'Mon Compte',
        'title3' => 'Mes Coupons',
        'title4' => 'Mes Coupons',
        'Unused Coupons' => 'Coupons Inutilisés',
        'Coupon Used' => 'Coupons Utilisés',
        'Coupon Code' => 'Code de coupons',
        'Coupon Type' => 'Type de coupons',
        'Coupon Value' => 'Valeur de coupons',
        'Terms & Conditions' => 'Termes & Conditions',
        'Valid From' => 'Valable à partir de',
        'Expiration Date' => 'Date d’expiration',
        'Created Date' => 'Date de Création',
        'Order Number' => 'Numéro de Commande',
        'Saving' => 'Économiser',
        'Used Date' => 'Date de l’utilisation',
        'conditions1' => 'Tous les articles à plein tarif',
        'conditions2' => 'Tous les articles',
    ),
);