<?php

return array(
    'en'=>array(
        'title1' => 'home',
        'title2' => 'my account',
        'history_title3' => 'order history',
        'history_title4' => 'Order History',
        'unpaid_title3' => 'unpaid orders',
        'unpaid_title4' => 'Unpaid Orders',
        'empty1' => ', you do not have any Orders. It′s time to do some shopping on Choies with your 15% off Coupon now.',
        'empty2' => 'To view the order details, please click the order number or "Order Details" button',
        'Product Details' => 'Product Details',
        'Price' =>  'Price',
        'QTY' =>  'QTY',
        'Shipping' =>  'Shipping',
        'Order Total' =>  'Order Total',
        'Order Status' =>  'Order Status',
        'Action' =>  'Action',

        'Order No' => 'Order No.',
        'Order Time' => 'Order Time:',
        'Order Total1' => 'Order Total:',
        'Shipping Fee' => 'Shipping Fee:',
        'Order Status1' => 'Order Status:',
        'Order Details' => 'Order Details',
        'to pay' => 'to pay',
        'Out of stock' => 'Out of stock',
        'Reviewed' => 'Reviewed',
        'Track Order' => 'Track Order',
        'Tracking1' => 'Tracking Details as follows are recently updated, please',
        'Tracking2' => 'click here',
        'Tracking3' => 'to check all detals',
    ),
    'es' => array(
        'title1' => 'PÁGINA DE INICIO',
        'title2' => 'RESUMEN DE CUENTA',
        'history_title3' => 'Historial De Pedidos',
        'history_title4' => 'Historial De Pedidos',
        'unpaid_title3' => 'Pedidos Pendientes de Pago',
        'unpaid_title4' => 'Pedidos Pendientes de Pago',
        'empty1' => ', no tiene ningún pedido actualmente. Es el momento de hacer alguna compra en Choies con su cupón 15% de descuento ahora.',
        'empty2' => 'Para ver los detalles del pedido, por favor haga clic en el número de pedido o el botón "Detalles de Pedido".',
        'Product Details' => 'Detalles de Products',
        'Price' =>  'Precio',
        'QTY' =>  'Cantidad',
        'Shipping' =>  'Envío',
        'Order Total' =>  'Total de Pedido',
        'Order Status' =>  'Estado de Pedido',
        'Action' =>  'Acción',

        'Order No' => 'No. de Pedido:',
        'Order Time' => 'Fecha de Pedido:',
        'Order Details' => 'Detalles de Pedido',
        'to pay' => 'Pagar',
        'Out of stock' => 'Fuera de Stock',
        'Reviewed' => 'Comentado',
        'Track Order' => 'Rastrear Pedido',
        'Tracking1' => 'Los Detalles de seguimiento de la siguiente se actualizan recientemente, por favor',
        'Tracking2' => 'haga clic aquí',
        'Tracking3' => 'para ver todos los detalles',
        'Order Total1' => 'Pedido Total:',
        'Shipping Fee' => 'El costo de envío:',
        'Order Status1' => 'Estado de Pedido:',
    ),
    'de' => array(
        'title1' => 'Homepage',
        'title2' => 'KONTOÜBERSICHT',
        'history_title3' => 'Bestellhistorie',
        'history_title4' => 'Bestellhistorie',
        'unpaid_title3' => 'Unbezahlte Bestellungen',
        'unpaid_title4' => 'Unbezahlte Bestellungen',
        'empty1' => ', Sie haben noch keine Bestellungen. Es ist Zeit zum Einkaufen auf Choies mit 15% Rabatt Code jetzt.',
        'empty2' => 'Um die Details der Bestellung zu sehen, klicken Sie bitte die Bestellnummer oder Button "Details Sehen".',
        'Product Details' => 'Produktdetails',
        'Price' =>  'Preis',
        'QTY' =>  'Anzahl',
        'Shipping' =>  'Lieferung',
        'Order Total' =>  'Gesamtsumme',
        'Order Status' =>  'Bestellstatus',
        'Action' =>  'Aktion',

        'Order No' => 'Bestellnummer:',
        'Order Time' => 'Bestellzeit:',
        'Order Details' => 'Bestelldetails',

        'to pay' => 'BEZAHLEN',
        'Out of stock' => 'Out of stock',
        'Reviewed' => 'Rezensiert',
        'Track Order' => 'Bestellung Verfolgen',
        'Tracking1' => 'Verfolgung Informationen wie folgt sind kürzlich aktualisiert, ',
        'Tracking2' => 'klicken Sie bitte hier',
        'Tracking3' => ', um alle Details zu prüfen.',
        'Order Total1' => 'Gesamtsumme:',
        'Shipping Fee' => 'Versandkosten:',
        'Order Status1' => 'Bestellstatus:',
    ),
    'fr' => array(
        'title1' => 'Accueil',
        'title2' => 'Mon Compte',
        'history_title3' => 'Historique de Commandes',
        'history_title4' => 'Historique de Commandes',
        'unpaid_title3' => 'Commandes Non Payées',
        'unpaid_title4' => 'Commandes Non Payées',
        'empty1' => ", vous n'avez pas encore de commandes. C'est le temps de faire des achats sur Choies avec votre coupon-rabais de 15% maintenant.",
        'empty2' => 'Pour voir les détails de la commande, veuillez cliquer sur le numéro de commande ou bouton "Détails de la commande".',
        'Product Details' => 'Détails De Produit',
        'Price' =>  'Prix',
        'QTY' =>  'QTÉ',
        'Shipping' =>  'Livraison',
        'Order Total' =>  'Total',
        'Order Status' =>  'Statut De Commande',
        'Action' =>  'Action',

        'Order No' => 'N° De Commande',
        'Order Time' => 'Date De Commande:',
        'Order Details' => 'Détails De Commande',

        'to pay' => 'Payer',
        'Out of stock' => 'En rupture de stock',
        'Reviewed' => 'commenté',
        'Track Order' => 'Suivi de Commande',
        'Tracking1' => 'Les détails de suivi au dessous sont mis au jour récemment,',
        'Tracking2' => 'cliquer ici',
        'Tracking3' => 'pour vérifier tous les détails.',
        'Order Total1' => 'Total:',
        'Shipping Fee' => 'Livraison:',
        'Order Status1' => 'Statut De Commande:',
    ),

);