<?php

return array(
    'en' => array(
      'title1' => 'home',
      'title2' => 'order history',
      'title3' => 'order details',
      'title4' => 'Order Details',

      'Order Placement' => 'Order Placement',
      'Order Processing' => 'Order Processing',
      'Order Shipped' => 'Order Shipped',
      'Order No' => 'Order No.:',
      'Order Date' => 'Order Date:',

      'Name' => 'Name',
      'Price' => 'Price',
      'Quantity' => 'Quantity',
      'QTY' => 'QTY',
      'Subtotal' => 'Subtotal',
      'Order Status' => 'Order Status',
      'Tracking No.' => 'Tracking No.',
      'Action' => 'Action',
        'Out of stock' => 'Out of stock',
      'Share With' => 'Share With',
      'Reviewed' => 'Reviewed',
      'Shipping' => 'Shipping',
      'Pay with Coupons & Points' => 'Pay with Coupons & Points:',
      'Wholesave' => 'Wholesale Saving',
      'Order Total' => 'Order Total',
      'FREE EXPRESS SHIPPING on orders $79+ to US / TW / HK' => 'FREE EXPRESS SHIPPING on orders $79+ to US / TW / HK ',
      'SHIPPING ADDRESS' => 'SHIPPING ADDRESS',
      'Shipping Details' => 'Shipping Details',
      'Payment Method' => 'Payment Method',
      'You have paid' => 'You have paid',
      'with' => 'with',
      'You will pay' => 'You will pay',
      'title5' => 'If you don\'t have a PayPal account, you can also pay via PayPal with your credit card
            or bank debit card.',
      'title6' => 'Sorry, there are "out of stock" items in this order, please make a new one.',
      'Message' => 'Message',
      '5-100 characters' => '5-100 characters',
      'Edit' => 'Edit',
        'Submit' => 'Submit',
      'Guaranteed Secure Checkout' => 'Guaranteed Secure Checkout',
      'Free Worldwide Shipping' => 'Free Worldwide Shipping',
      '60 Day Money Back Warranty' => '60 Day Money Back Warranty',
      'shipping insurance' => 'shipping insurance',
      'Pay with Coupons' => 'Pay with Coupons',
      'Shipping Method' => 'Shipping Method',
      'Shipping Address' => 'Shipping Address',

        'Confirm and pay' => 'Confirm and pay',
        'PAY NOW' => 'PAY NOW',
  ),
    'de' => array(
        'title1' => 'Homepage',
        'title2' => 'KONTOÜBERSICHT',
        'title3' => 'Bestelldetails',
        'title4' => 'Bestelldetails',

        'Order Placement' => 'Bestellung Machen',
        'Order Processing' => 'Bestellung Bearbeiten',
        'Order Shipped' => 'Bestellung Versand',
        'Order No' => 'Bestellnummer:',
        'Order Date' => 'Bestelldatum:',

        'Name' => 'NAME',
        'Price' => 'PREIS',
        'Quantity' => 'Menge',
        'QTY' => 'Menge',
        'Subtotal' => 'Zwischensumme',
        'Order Status' => 'Bestellstatus',
        'Tracking No.' => 'Sendungnummer',
        'Action' => 'Aktion',
        'Out of stock' => 'Nicht Auf Lager',
        'Share With' => 'Teilen Mit',
        'Reviewed' => 'Rezensiert',
        'Shipping' => 'Lieferung',
        'Pay with Coupons & Points' => 'Gutscheine & Punkte eingelöst:',
        'Wholesave' => 'ARTIKEL Einsparungen',
        'Order Total' => 'Gesamtsumme',
        'FREE EXPRESS SHIPPING on orders $79+ to US / TW / HK' => '',
        'SHIPPING ADDRESS' => 'LIEFERUNG ADRESSE',
        'Shipping Details' => 'Versandart',
        'Payment Method' => 'Zahlungsmethode',
        'You have paid' => 'Sie haben',
        'with' => 'bezahlen mit',
        'You will pay' => 'Sie werden',
        'title5' => 'Wenn Sie kein PayPal-Konto haben, können Sie auch per PayPal mit Ihrer Kreditkarte oder EC-Karte bezahlen.',
        'title6' => 'Sorry, there are "out of stock" items in this order, please make a new one.',
        'Message' => 'Nachricht',
        '5-100 characters' => '5-100 Zeichen',
        'Edit' => 'Editieren',
        'Submit' => 'SENDEN',
        'Guaranteed Secure Checkout' => 'Garantierter Datenschutz Kasse',
        'Free Worldwide Shipping' => 'Weltweit Versandkostenfrei',
        '60 Day Money Back Warranty' => '60 Tage Geld-Zurück-Garantie',
        'shipping insurance' => 'Versandversicherung',
        'Pay with Coupons' => 'Gutscheine & Punkte eingelöst',
        'Shipping Method' => 'Gesamtsumme',
        'Shipping Address' => 'LIEFERUNG ADRESSE',

        'Confirm and pay' => 'Bestätigen und Bezahlen',
        'Pay NOW' => 'Bestätigen und Bezahlen'
    ),
    'es' => array(
        'title1' => 'PÁGINA DE INICIO',
        'title2' => 'RESUMEN DE CUENTA',
        'title3' => 'Detalles de Pedido',
        'title4' => 'Detalles de Pedido',

        'Order Placement' => 'Realizar el Pedido',
        'Order Processing' => 'Procesamiento de Pedido',
        'Order Shipped' => 'Envío de Pedido',
        'Order No' => 'No. de Pedido:',
        'Order Date' => 'Fecha de Pedido:',

        'Name' => 'Nombre',
        'Price' => 'Precio',
        'Quantity' => 'Cantidad',
        'QTY' => 'Cantidad',
        'Subtotal' => 'Subtotal',
        'Order Status' => 'Estado de Pedido',
        'Tracking No.' => 'No. de seguimiento',
        'Action' => 'Acción',
        'Out of stock' => 'Fuera De Stock',
        'Share With' => 'Compartir',
        'Reviewed' => 'Comentado',
        'Shipping' => 'Envío',
        'Pay with Coupons & Points' => 'Pagar Con Copónes:',
        'Wholesave' => 'Wholesale Saving',
        'Order Total' => 'Total',
        'FREE EXPRESS SHIPPING on orders $79+ to US / TW / HK' => '',
        'SHIPPING ADDRESS' => 'DIRECCIÓN DE ENVÍO',
        'Shipping Details' => 'DETALLES DE ENVÍO',
        'Payment Method' => 'MÉTODO DE PAGO',
        'You have paid' => 'Ya haya pagado',
        'with' => 'con',
        'You will pay' => 'Deseo pagar',
        'title5' => 'Usted puede solicitar los puntos que equivalen a sólo el 10% de valor de su pedido.Completa tu perfil, se le otorgará 500 puntos para canjear tu primer pedido.',
        'title6' => 'Disculpe, hay algunos artículos que"están fuera de stock" en su pedido, por favor haga un nuevo.',
        'Message' => 'Mensaje',
        '5-100 characters' => '5-100 caracteres',
        'Edit' => 'EDITAR',
        'Submit' => 'PRESENTAR',
        'Guaranteed Secure Checkout' => 'Pago Seguro Garantizado',
        'Free Worldwide Shipping' => 'Envío Gratis Mundial',
        '60 Day Money Back Warranty' => '60 Días De Rembolso Garantizado',
        'shipping insurance' => 'Seguros de Envío',
        'Pay with Coupons' => 'Pagar Con Copónes',
        'Shipping Method' => 'MÉTODOS DE ENVÍO',
        'Shipping Address' => 'ENVÍO DIRECCIÓNES',

        'Confirm and pay' => 'Confirmar y Pagar',
        'PAY NOW' => 'Confirmar y Pagar',
    ),
    'fr' => array(
        'title1' => 'Accueil',
        'title2' => 'Historique de Commandes',
        'title3' => 'Détails De Commande',
        'title4' => 'Détails De Commande',

        'Order Placement' => 'Placement De Commande',
        'Order Processing' => 'Traitement De Commande',
        'Order Shipped' => 'Livraison',
        'Order No' => 'N° de Commande:',
        'Order Date' => 'Date de Commande:',

        'Name' => 'Nom',
        'Price' => 'Prix',
        'Quantity' => 'Quantité',
        'QTY' => 'QTÉ',
        'Subtotal' => 'Sous-Total',
        'Order Status' => 'Statut',
        'Tracking No.' => 'N° De Suivi',
        'Action' => 'Action',
        'Out of stock' => 'Indisponible',
        'Share With' => 'Partager Avec',
        'Reviewed' => 'commenter',
        'Shipping' => 'Livraison',
        'Pay with Coupons & Points' => 'COUPONS & POINTS:',
        'Wholesave' => 'Sale Items Saving',
        'Order Total' => 'TOTAL',
        'FREE EXPRESS SHIPPING on orders $79+ to US / TW / HK' => '',
        'SHIPPING ADDRESS' => 'ADRESSE DE LIVRAISON',
        'Shipping Details' => 'DÉTAILS DE LIVRAISON',
        'Payment Method' => 'MÉTHODE DE PAIEMENT',
        'You have paid' => 'Vous paierez',
        'with' => 'avec',
        'You will pay' => 'Vous paierez',
        'title5' => 'Si vous ne possédez pas de compte PayPal, vous pouvez également payer via PayPal avec votre carte de crédit ou carte de débit bancaire.
    or bank debit card.',
        'title6' => 'Désolé, il y a "rupture de stock" articles dans cette commande, faire un nouveau s\'il vous plaît.',
        'Message' => 'Message',
        '5-100 characters' => '5-100 caractères',
        'Edit' => 'Modifier',
        'Submit' => 'SOUMETTRE',
        'Guaranteed Secure Checkout' => 'Paiement Sécurisé',
        'Free Worldwide Shipping' => 'Livraison Gratuite',
        '60 Day Money Back Warranty' => 'Garantie De Remboursement De 60 Jours',
        'shipping insurance' => 'assurance transport',
        'Pay with Coupons' => 'COUPONS & POINTS',
        'Shipping Method' => 'Livraison',
        'Shipping Address' => 'ADRESSE DE LIVRAISON',

        'Confirm and pay' => 'Confirmer et payer',
        'PAY NOW' => 'Confirmer et payer',

    ),
);