<?php

return array(
    'en' => array(
        'title1' => 'home',
        'title2' => 'my account',
        'title3' => 'points history',
        'title4' => 'Points History',
        'title5' => 'Points Balance Summary:',
        'Points Rewarded' => 'Points Rewarded:',
        'Used Points' => 'Used Points:',
        'Activated Points to use' => 'Activated Points to use:',
        'Savings' => 'Savings:',
        'Points Balance' => 'Points Balance',
        'Points Rewarded1' => 'Points Rewarded',
        'Points Used' => 'Points Used',
        'Points Date' => 'Points Date',
        'Points Rewarded / Used Source' => 'Points Rewarded / Used Source',
        'Points Status' => 'Points Status',
        'Save' => 'Save',
        'Rewarded / Used Type' => 'Rewarded / Used Type',
        'Order Number' => 'Order Number:',
    ),
    'es' => array(
        'title1' => 'Página de Inicio',
        'title2' => 'RESUMEN DE CUENTA',
        'title3' => 'Historial De Puntos',
        'title4' => 'Historial De Puntos',
        'title5' => 'RESUMEN DE PUNTOS:',
        'Points Rewarded' => 'Puntos Recompensados:',
        'Used Points' => 'Puntos Usados:',
        'Activated Points to use' => 'Puntos Activados Para Utilizar:',
        'Savings' => 'Ahorro:',
        'Points Balance' => 'Blanza de Puntos',
        'Points Rewarded1' => 'Puntos Recompensados',
        'Points Used' => 'Puntos Usados',
        'Points Date' => 'Fecha De Puntos',
        'Points Rewarded / Used Source' => 'Puntos Recompensados/ Fuente de Uso',
        'Points Status' => 'Estado De Puntos',
        'Save' => 'Ahorro',
        'Rewarded / Used Type' => 'Recompensado / Tipo de Uso',
        'Order Number' => 'Numero De Pedido:',
    ),
    'de' => array(
        'title1' => 'Homepage',
        'title2' => 'KONTOÜBERSICHT',
        'title3' => 'Punkte Historie',
        'title4' => 'Punkte Historie',
        'title5' => 'PUNKTE BILANZ ZUSAMMENFASSEN:',
        'Points Rewarded' => 'Punkte Erhalten:',
        'Used Points' => 'Verwendete Punkte:',
        'Activated Points to use' => 'Aktivierte Punkte zu benutzen:',
        'Savings' => 'Einsparungen:',
        'Points Balance' => 'Punkt Bilanz',
        'Points Rewarded1' => 'Punkte Erhalten',
        'Points Used' => 'Punkte Verwendet',
        'Points Date' => 'Punkte Datum',
        'Points Rewarded / Used Source' => 'Punkte Erhalten',
        'Points Status' => 'Punkte Status',
        'Points  Used' => 'Punkte Verwendete',
        'Save' => 'Speichern',
        'Rewarded / Used Type' => 'Belohnt / Verwendet Typ',
        'Order Number' => 'Bestellnummer:',
    ),
    'fr' => array(
        'title1' => 'Accueil',
        'title2' => 'Mon Compte',
        'title3' => 'Historique de Points',
        'title4' => 'Historique de Points',
        'title5' => 'RELEVÉ DE SOLDE DE POINTS:',
        'Points Rewarded' => 'Points Récompensés:',
        'Used Points' => 'Points Utilisés:',
        'Activated Points to use' => 'Points activés pour utiliser:',
        'Savings' => 'Économiser:',
        'Points Balance' => 'Solde de Points',
        'Points Rewarded1' => 'Points Récompensés',
        'Points Used' => 'Points Utilisés',
        'Points Date' => 'Date de Points',
        'Points Rewarded / Used Source' => 'Points Récompensés / Source Utilisé',
        'Points Status' => 'État de points',
        'Save' => 'Économiser',
        'Rewarded / Used Type' => 'Type récompensé/utilisé',
        'Order Number' => 'Numéro de Commande:',
    ),
);