<?php

return array(
    'en' => array(
        'title1' => 'home',
        'title2' => 'my account',
        'title3' => 'Hi,',
        'title4' => '. Welcome to Choies.',
        'title5' => 'VIP Member or Not:',
        'Expires on' => 'Expires on:',
        'Privileges' => 'Privileges',
        'VIP Level' => 'VIP Level',
        'Accumulated Transaction Amount' => 'Accumulated Transaction Amount',
        'Extra Discounts for Items' => 'Extra Discounts for Items',
        'Points Use Permissions' => 'Points Use Permissions',
        'Order Points Reward' => 'Order Points Reward',
        'Other Privileges' => 'Other Privileges',
        'Non-VIP' => 'Non-VIP',
        '$0' => '$0',
        'You may apply Points equaling up to only 10% of your order value' => 'You may apply Points equaling up to only 10% of your order value.',
        '$1 = 1 points' => '$1 = 1 points',
        '15% off Coupon Code' => '15% off Coupon Code',
        'VIP' => 'VIP',
        '$1 - $199' => '$1 - $199',
        'Get double shopping points during major holidays' => 'Get double shopping points during major holidays.',
        'Special birthday gift' => 'Special birthday gift.',
        'And More...' => 'And More...',
        'Bronze VIP' => 'Bronze VIP',
        '$199 - $399' => '$199 - $399',
        '5% OFF' => '5% OFF',
        'Silver VIP' => 'Silver VIP',
        '$399 - $599' => '$399 - $599',
        '8% OFF' => '8% OFF',
        'Gold VIP' => 'Gold VIP',
        '$599 - $1999' => '$599 - $1999',
        '10% OFF' => '10% OFF',
        'Diamond VIP' => 'Diamond VIP',
        '$1999' => '$1999',
        '15% OFF' => '15% OFF',

        'Below are your recent orders' => 'Below are your recent orders:',
        'Order Date' => 'Order Date',
        'Order No' => 'Order No.',
        'Order Total' => 'Order Total',
        'Shipping' => 'Shipping',
        'Order Status' => 'Order Status',
        'Action' => 'Action',

        'Track' => 'Track',
        'View Details' => 'View Details',
        'To pay' => 'To pay',
        'Recently Viewed' => 'Recently Viewed',
        'Best Seller' => 'Best Seller',
    ),
    'es' => array(
        'title1' => 'Página de Inicio',
        'title2' => 'RESUMEN De LA CUENTA',
        'title3' => 'Hi,',
        'title4' => '. Bienvenido a Choies.',
        'title5' => 'Miembro de VIP o No:',
        'Expires on' => 'Vence en:',
        'Privileges' => 'Privilegios',
        'VIP Level' => 'VIP Nivel',
        'Accumulated Transaction Amount' => 'Acumulado Transacción Monto',
        'Extra Discounts for Items' => 'Descuentos Adicionales para Artículos',
        'Points Use Permissions' => 'Puntos Uso Permitidos',
        'Order Points Reward' => 'Puntos Recompensados de Pedido',
        'Other Privileges' => 'Otros Privilegios',
        'Non-VIP' => 'No VIP',
        '$0' => '$0',
        'You may apply Points equaling up to only 10% of your order value' => 'Usted puede solicitar puntos equivalen a sólo el 10% de su valor de la pedido.',
        '$1 = 1 points' => '$1 = 1 puntos',
        '15% off Coupon Code' => '15% de descuento  código promocional',
        'VIP' => 'VIP',
        '$1 - $199' => '$1 - $199',
        'Get double shopping points during major holidays' => 'Consigue puntos comerciales dobles durante los principales días festivos.',
        'Special birthday gift' => 'Regalo de cumpleaños especial.',
        'And More...' => 'Y más...',
        'Bronze VIP' => 'VIP Bronce',
        '$199 - $399' => '$199 - $399',
        '5% OFF' => '5% menos',
        'Silver VIP' => 'VIP Plata',
        '$399 - $599' => '$399 - $599',
        '8% OFF' => '8% menos',
        'Gold VIP' => 'VIP Oro',
        '$599 - $1999' => '$599 - $1999',
        '10% OFF' => '10% menos',
        'Diamond VIP' => 'VIP Diamante',
        '$1999' => '$1999',
        '15% OFF' => '15% menos',

        'Below are your recent orders' => 'Los siguientes son sus pedidos recientes:',
        'Order Date' => 'Fecha de Pedido',
        'Order No' => 'No. de Pedido',
        'Order Total' => 'Total de Pedido',
        'Shipping' => 'Envío',
        'Order Status' => 'Estado de Pedido',
        'Action' => 'Acción',

        'Track' => 'RASTREAR',
        'View Details' => 'Detalles de Pedido',
        'To pay' => 'Pagar',
        'Recently Viewed' => 'Visitado Recientemente',
        'Best Seller' => 'Los Más Vendidos',
    ),
    'de' => array(
        'title1' => 'Homepage',
        'title2' => 'KONTOÜBERSICHT',
        'title3' => 'Hi,',
        'title4' => '. Welcome to Choies.',
        'title5' => 'VIP Member or Not:',
        'Expires on' => 'Expires on:',
        'Privileges' => 'Privilegien',
        'VIP Level' => 'VIP Level',
        'Accumulated Transaction Amount' => 'Kumulierte Transaktionsbetrag',
        'Extra Discounts for Items' => 'Zusätzliche Rabatte für Artikel',
        'Points Use Permissions' => 'Punkte-Verwenden Berechtigungen',
        'Order Points Reward' => 'Bestellung-Punkte Belohnung',
        'Other Privileges' => 'Andere Vorrechte',
        'Non-VIP' => 'Nicht-VIP',
        '$0' => '$0',
        'You may apply Points equaling up to only 10% of your order value' => 'Sie können Punkte bis zu insgesamt 10% des Auftragswertes anwenden.',
        '$1 = 1 points' => '$1 = 1 Punkt',
        '15% off Coupon Code' => '15% Rabatt Code',
        'VIP' => 'VIP',
        '$1 - $199' => '$1 - $199',
        'Get double shopping points during major holidays' => 'Sie können Doppel Einkaufspunkte während der großen Ferien erhalten.',
        'Special birthday gift' => 'Besondere Geburtstagsgeschenk.',
        'And More...' => 'Und mehr...',
        'Bronze VIP' => 'Bronze VIP',
        '$199 - $399' => '$199 - $399',
        '5% OFF' => '5% Rabatt',
        'Silver VIP' => 'Silber VIP',
        '$399 - $599' => '$399 - $599',
        '8% OFF' => '8% Rabatt',
        'Gold VIP' => 'Gold VIP',
        '$599 - $1999' => '$599 - $1999',
        '10% OFF' => '10% Rabatt',
        'Diamond VIP' => 'Diamant VIP',
        '$1999' => '$1999',
        '15% OFF' => '15% Rabatt',

        'Below are your recent orders' => 'Below are your recent orders:',
        'Order Date' => 'Bestelldatum',
        'Order No' => 'Bestellnummer',
        'Order Total' => 'Gesamtsumme',
        'Shipping' => 'Lieferung',
        'Order Status' => 'Bestellstatus',
        'Action' => 'Aktion',

        'Track' => 'Verfolgen',
        'View Details' => 'Bestelldetails',
        'To pay' => 'BEZAHLEN',
        'Recently Viewed' => 'Kürzlich Rezensiert',
        'Best Seller' => 'Bestseller',
    ),
    'fr' => array(
        'title1' => 'Accueil',
        'title2' => 'Mon Compte',
        'title3' => 'Bonjour,',
        'title4' => '. Bienvenue à CHOICES.',
        'title5' => 'Membre VIP ou Non:',
        'Expires on' => 'Expire le:',
        'Privileges' => 'Privileges',
        'VIP Level' => 'Niveau VIP',
        'Accumulated Transaction Amount' => 'Montant accumulé  de transaction',
        'Extra Discounts for Items' => 'Rabais supplémentaires sur articles',
        'Points Use Permissions' => "Autorisation de l'utilisation des points",
        'Order Points Reward' => 'Points de récompense de commande',
        'Other Privileges' => "D'autres privilèges",
        'Non-VIP' => 'Non-VIP',
        '$0' => '$0',
        'You may apply Points equaling up to only 10% of your order value' => 'Vous pouvez utiliser les points équivalant à seulement 10% de la valeur de votre commande.',
        '$1 = 1 points' => '$1 = 1 points',
        '15% off Coupon Code' => 'Bon de réduction de 15%',
        'VIP' => 'VIP',
        '$1 - $199' => '$1 - $199',
        'Get double shopping points during major holidays' => 'Obtenir des points doubles d\'achat pendant les grandes fêtes.',
        'Special birthday gift' => "Cadeau d'anniversaire.",
        'And More...' => 'Et plus...',
        'Bronze VIP' => 'VIP Bronze',
        '$199 - $399' => '$199 - $399',
        '5% OFF' => '5% de réduction',
        'Silver VIP' => 'VIP Argent',
        '$399 - $599' => '$399 - $599',
        '8% OFF' => '8% de réduction',
        'Gold VIP' => 'VIP Or',
        '$599 - $1999' => '$599 - $1999',
        '10% OFF' => '10% de réduction',
        'Diamond VIP' => 'VIP Diamant',
        '$1999' => '$1999',
        '15% OFF' => '15% de réduction',

        'Below are your recent orders' => 'Ci-dessous sont vos commandes récentes:',
        'Order Date' => 'Date De Commande',
        'Order No' => 'No. De Commande',
        'Order Total' => 'Total',
        'Shipping' => 'Livraison',
        'Order Status' => 'Statut De Commande',
        'Action' => 'Action',

        'Track' => 'SUIVRE',
        'View Details' => 'Détails De Commande',
        'To pay' => 'Payer',
        'Recently Viewed' => 'Consultés récemment',
        'Best Seller' => 'Meilleures Ventes',
    ),
);