<?php

return array(
    'en' => array(
        'title1' => 'home',
        'title2' => 'my account',
        'title3' => 'wish list',
        'title4' => 'Wishlist',
        'title5' => 'You may add products to your wishlist for later view or purchase!',
        'Product Info' => 'Product Info',
        'Availability' => 'Availability',
        'Price' => 'Price',
        'Action' => 'Action',
        'Item' => 'Item#:',
        'View Details' => 'View Details',
        'In Stock' => 'In Stock',
        'Out Stock' => 'Out Stock',
        'ADD TO BAG' => 'ADD TO BAG',
    ),
    'es' => array(
        'title1' => 'Página de Inicio',
        'title2' => 'RESUMEN DE CUENTA',
        'title3' => 'Lista De Deseos',
        'title4' => 'Lista De Deseos',
        'title5' => '¡Usted puede añadir productos a su lista de deseos para la visión posterior o la compra!',
        'Product Info' => 'Información De Producto',
        'Availability' => 'Disponibilidad',
        'Price' => 'Precio',
        'Action' => 'Acción',
        'Item' => 'artículo#:',
        'View Details' => 'View Details',
        'In Stock' => 'En Stock',
        'Out Stock' => 'Fuera De Stock',
        'ADD TO BAG' => 'Ver Detalles',
    ),
    'de' => array(
        'title1' => 'Homepage',
        'title2' => 'KONTOÜBERSICHT',
        'title3' => 'Wunschliste',
        'title4' => 'Wunschliste',
        'title5' => 'Sie können Artikel zu Ihrer Wunschliste für spätere Ansicht oder Einkaufen addieren!',
        'Product Info' => 'Produkt-Info',
        'Availability' => 'Verfügbarkeit',
        'Price' => 'Preis',
        'Action' => 'Aktion',
        'Item' => 'Artikel#:',
        'View Details' => 'View Details',
        'In Stock' => 'Auf Lager',
        'Out Stock' => 'Nicht Auf Lager',
        'ADD TO BAG' => 'Details Sehen',
    ),
    'fr' => array(
        'title1' => 'Accueil',
        'title2' => 'Mon Compte',
        'title3' => 'Liste d’envies',
        'title4' => 'Liste d’envies',
        'title5' => 'Vous pouvez ajouter les produits à votre liste d’envies pour les acheter plus tard!',
        'Product Info' => 'Info de produit',
        'Availability' => 'Disponibilité',
        'Price' => 'Prix',
        'Action' => 'Action',
        'Item' => 'Article#:',
        'View Details' => 'Voir les Détails',
        'In Stock' => 'En Stock',
        'Out Stock' => 'En rupture de Stock',
        'ADD TO BAG' => 'AJOUTER AU PANIER',
    ),
);