<div id="container">
        <div class=" fix">
                <div id="main">
                        <div class="crumb"><a href="<?php echo LANGPATH; ?>/" class="home">Home</a>&gt;<span class="current">Privacy &amp; Disclaimer</span></div>
                        <div class="help">
                                <h3><span><a>Privacy &amp; Disclaimer</a></span></h3>
                                <div>
                                        <p>ukhollister.co.uk. is strongly committed to protecting your privacy and providing a safe online experience for all our users. This policy applies to information collected online through our website, which includes all of the Guide-Sites and governs online data collection and usage by us. Please read the complete our online privacy policy below and contact us if you have any questions. </p>
                                        <h4>What information do we collect?</h4>
                                        <p>We collect information about you to process your order and provide you with the most efficient and enhanced service. We collect personally identifiable information such as names, email addresses and demographic information such as age, gender and zip code. We also may collect your IP address, domain name, access times and referring website address. This information is collected both during registration on a page or in response to specific requests, for example when signing up for a newsletter. Information collected at ukhollister.co.uk. will be available within the ukhollister.co.uk. family of websites. </p>
                                        <h4>What the data will be used for?</h4>
                                        <p>We use personal information so that we may display custom, personalized content to our visitors and send newsletters, emails, features, promotional material, surveys and other updates to our users. You may, at any time, opt out of receiving such information. We also use collected information to evaluate and administer our service, respond to any problems that may arise and to gauge user trends to determine what part of our services are most popular with you. </p>
                                        <p>We reserve the right to use or disclose any information without notice or consent as needed to satisfy any law, regulation or legal request; to conduct investigations of consumer complaints or possible breaches of law; to protect the integrity of our site and our property; to protect the safety of our visitors or others; to fulfill your requests; or to cooperate in any legal investigation. </p>
                                        <p>You should be aware that if you voluntarily disclose information online (whether through ukhollister.co.uk. services or any other services available online), personal or otherwise, that information can be collected and used by others. For example, if you use chat, forums, bulletin boards, and your e-mail or if you post personal information online, you may receive unsolicited messages from others. ukhollister.co.uk. has no control over this use of your personal information.</p>
                                        <h4>COOKIES</h4>
                                        <p>When you enter this website, we will use cookies. Cookies are tiny text files that identify your computer to our server. These cookies in no way allow us access to your computer and do not store any details related to you or your credit cards. They are used to record the length of time and the areas of your visit on the website, which provides us with useful usage information that helps us make our site more accessible to our users in line with their needs. The use of cookies also helps us to improve the quality of service that we provide.</p>
                                        <h4>How Do We Use the Information We Collect?</h4>
                                        <p>We use your personally identifiable information to provide you with the information or content that you have requested. We will not send you any marketing material unless you have requested it through this Web Site.</p>
                                        <p>Further information about how we use your personal information is provided on our web-pages at the point you submit your personal information to us.</p>
                                        <p>We use non-identifying information collected on our Web Site in the aggregate to better understand your use of the Web Site and to enhance your enjoyment and experience. For example, we may use the information to improve the design and content of our Web Site or to analyze the programs and services that we offer.</p>
                                        <p>We may employ other companies and individuals to perform functions on our behalf. Our employees, agents and contractors who have access to personally identifiable information are required to protect the information in a manner that is consistent with this Privacy Statement.</p>
                                        <p>We may provide access to your personally identifiable information when legally required to do so, to co-operate with police investigations or other legal proceedings, to protect against misuse or unauthorized use of this Web Site, to limit our legal liability and protect our rights, or to protect the rights and safety of visitors to this Web Site or the public. In those instances, the information is provided only for those limited purposes.</p>
                                        <p>We will not share your personally identifiable information in ways unrelated to those described above without providing you with an opportunity to opt out of such use or otherwise prohibit such unrelated uses.</p>
                                        <h4>How Do You Access and/or Modify Your Personal Information?</h4>
                                        <p>If you visit this Web Site and volunteer personally identifiable information, you may modify, update or delete such information at any time by visiting ukhollister.co.uk. where you will have the opportunity to access and revise certain personally identifiable information. You should be aware, however, that it is not always possible to completely remove or modify information in our databases.</p>
                                        <h4>Data Security</h4>
                                        <p>ukhollister.co.uk. employees are made aware of its privacy practices through periodic communications and training. We limit access to private and confidential data only to those employees with a specific need to retrieve this information and we store data on multiple service systems, in controlled, secure environments. To maintain our level of security, we conduct both internal reviews and external audits of our security measures and procedures on a regular basis. </p>
                                        <p>We utilize industry-standard Secure Sockets Layer (SSL) technology to allow for the encryption of potentially sensitive information such as your name, address and other critically sensitive information like your credit card details during checkout. Information passed between your computer and our website cannot be read in the event someone else intercepts it.</p>
                                        <p>A padlock will also be visible in the bottom right of your web browser, which means you are in secure mode. The padlock should always be locked up when you are entering personal or payment details. </p>
                                        <p>We do not store your card details (that is why we ask for them for every order placed).</p>
                                        <h4>Disclaimer</h4>
                                        <p>This website is compiled by ukhollister.co.uk, an online electronic product retailer. It aims to provide accurate information and makes every effort to achieve this, however the publishers cannot accept any liability in respect of errors or omissions.</p>
                                        <p>All information is published in good faith without responsibility for loss occasioned by acting or refraining from action as a result of the content of this site. We are not responsible for the availability of access to this website. Accessing the data on this site signifies your acceptance of these conditions of use.</p>
                                        <p>In the unlikely event that you should experience any difficulties whilst using this website, please feel free to contact with us by <a href="#">Tickets system</a> or <a href="#">Online-support</a> with a full description of the problem.</p>
                                        <p>If you have any question or suggestion about our privacy policy, please feel free to contact with us by <a href="#">Tickets system</a> or <a href="#">Online-support</a>.</p>
                                </div>
                        </div>
                </div>
                <?php echo View::factory('doc/left'); ?>
        </div>
</div>