<section id="main">
    <!-- crumbs -->
    <div class="layout">
        <div class="crumbs fix">
            <div class="fll"><a href="<?php echo LANGPATH; ?>/">home</a>  >  VIP LEVEL & PRIVILEGES</div>
        </div>
    </div>

    <!-- main begin -->
    <section class="layout fix">
        <section id="container" class="flr">
            <div class="newin_banner">

                <img src="/uploads/1/files/<?php echo $index_banners[2]['image']; ?>" /><br><br>
                <a href="http://www.choies.com/customer/orders?policy" target="_blank"><img src="/images/docs/rate-order-win-100.jpg" /></a></div>
                <div class="doc_box">
                    <p>PURCHASE OR PAYMENT OF ANY KIND IS NECESSARY TO ENTER OR WIN THIS SWEEPSTAKES. More purchases within a month, more chances of winning.</p>
                    <p>These rules govern the Customer Product Review Sweepstakes (the "Sweepstakes") offered by Choies.com</p>
                    <p>Sweepstakes Period: Sweepstakes begins at 12:01 a.m. Eastern Time ("ET") on July 1st, 2014 and runs monthly. All entries become the property of Choies and will not be returned. Sponsor shall determine timeliness of entries in its sole discretion.</p>
                    <h4>1. Eligibility: Sweepstakes is open to worldwide customers.</h4>
                    <p>There are only one way to enter:<br />
                        Post A Product Review: Log on to www.choies.com during the Sweepstakes Period and either sign in if you are already a registered customer or register with choies.com. There is no cost to register. Then, post a review of any product you have successfully purchased and you will be automatically entered into the Sweepstakes. You may review as many products you have purchased as you wish and each product review will constitute one (1) entry. All product reviews must be in English, Spanish, French or German. Sponsor does not guarantee the public posting of any product review and reserves the right, in its sole discretion, not to post your review for any reason, including, but not limited to, if it contains any of the following types of content or violates the Terms and Conditions: any content that infringes upon the copyrights of any third parties; contains obscene, lewd or offensive language; comments on other retailers or websites; comments on competitive products or other products, pricing or availability.</p>
                    <p>• Entrant agrees that Choies is not responsible for any unauthorized use of product reviews by third parties.</p>
                    <p>• Multiple reviews of the same product are not valid. "SPAM" or fraudulent product reviews will not be posted and all entries from any such user will be void.</p>
                    <p>• Entries generated by a script, computer programs, macro, programmed, robotic or other automated means are void and will be disqualified.</p>
                    <p>• Entrants may not submit product reviews with multiple email addresses nor may entrants use any device or artifice to submit product reviews multiple times or as multiple entrants.</p>
                    <p>• Any entrant who attempts to submit product reviews with multiple email addresses, under multiple identities or uses any other device or artifice to submit product reviews multiple times or subvert the entry process will be disqualified from participation in the Sweepstakes, and all product reviews and entries submitted by that entrant will be void.</p>
                    <P><strong>2. Drawing:</strong> One (1) winner will be selected in a random drawing by the end of every month since July from eligible entries received. All decisions of the judges are final. Odds of winning will be determined by the number of eligible entries received. Prize consists of only those items specifically described as included in the prize.</P>
                    <p><strong>3. Prize:</strong> Winner will receive a $100 Choies' Gift Card. Retail value of prize is: $100.</p>
                    <p><strong>4. Notification:</strong> Potential winner will be notified by e-mail must respond to accept or decline the prize within seven (7) days of notification. If a potential winner cannot be contacted, does not timely respond or if prize or prize notification is returned as undeliverable, an alternate potential winner will be selected. Upon prize forfeiture, no payment or other compensation will be made to the original potential winner. </p>
                    <p><strong>5. Publicity:</strong> Acceptance of a prize constitutes consent to Sponsor's use of winner's name, likeness, photograph, voice, opinions and/or hometown and state for promotional purposes in any media, worldwide, (including but not limited to internet and television broadcast) without further consent or compensation except where prohibited.</p>
                    <p><strong>6. Privacy:</strong> Handling of all participant information, including e-mail addresses, will be consistent with the Choies' Privacy Policy. See http://www.choies.com/privacy-security</p> 
                    <p>Sponsor: Choies.com </p>
                </div>
            </div>
        </section>
        <?php echo View::factory('doc/left'); ?>
    </section>
</section>