<?php
defined('SYSPATH') OR die('No direct access allowed.');

return array(
    'country' => array(
        'GB' => 'en',
        'ES' => 'es',
        'FR' => 'fr',
        'DE' => 'de',
        'RU' => 'ru',
        'PL' => 'en',
        'AU' => 'en',
        'CA' => 'en',
        'IT' => 'en',
        'SE' => 'en',
        'DK' => 'en',
        'MX' => 'es',
        'BR' => 'en',
        'NO' => 'en',
        'NL' => 'en',
        'RO' => 'en',
        'CZ' => 'en',
        'PT' => 'en',
    ),
    'currency' => array(
        'GB' => 'GBP',
        'ES' => 'EUR',
        'FR' => 'EUR',
        'DE' => 'EUR',
        'RU' => 'RUB',
        'PL' => 'PLN',
        'AU' => 'AUD',
        'CA' => 'CAD',
        'IT' => 'EUR',
        'SE' => 'SEK',
        'DK' => 'DKK',
        'MX' => 'MXN',
        'BR' => 'BRL',
        'NO' => 'NOK',
        'NL' => 'EUR',
        'RO' => 'EUR',
        'CZ' => 'EUR',
        'PT' => 'EUR',
        'CH' => 'CHF',
        'SA' => 'SAR',
        'AR' => 'ARS',
        'JP' => 'JPY',
        'HK' => 'HKD',
    ),  
);
?>