<?php
defined('SYSPATH') OR die('No direct access allowed.');
/**
 * config every sites(use site_id as key)
 *
 * @package
 * @author    FangHao
 * @copyright    © 2010 Cofree Development Group
 * 键名有/的，都是链接
 */
return array(
        'en'=>array(
            'lang' => array(
                'quick' =>'Quick View',
                'addto' => 'Add to wishlist',	
                'onesize' => 'one size',			
            ),
			'payment'=> array(
				'choosecard' =>'Please choose card type',
				'choosecard1' =>'Please choose your credit card type.',
			),
            'customer' => array(
                'REGISTER' => 'REGISTER',
                'SIGN IN' => 'SIGN IN',
                'choieser' => 'choieser',
                'My Order' => 'My Order',
                'Track Order' => 'Track Order',
                'My Wishlist' => 'My Wishlist',
                'My Profile' => 'My Profile',
                'Sign Out' => 'Sign Out',
            ),
            'bag'=> array(
                'ITEM' => 'ITEM',
                'IN MY BAG' => 'IN MY BAG',
                'VIEW BAG & CHECKOUT' => 'VIEW BAG & CHECKOUT',
            ),
            'pc_content' => array(
                //分类导航链接1
                'first' => array(
                    'title1' => 'NEW IN',
                    'title_link' => '/daily-new',
                    'title2' => 'SHOP BY',
                    'content' => array(
                        '/daily-new/week2' => 'This Week',
                        '/daily-new/week1' => 'Last Week',
                        '/daily-new/month' => 'Last Month',
                    ),
                ),
                //分类导航链接2
                'second' => array(
                    'title1' => 'CLOTHING',
                    'title_link' => '/clothing-c-615',
                    'title2' => 'SHOP BY CATEGORY',
                    'content' => array(
                        '/dresses-c-92'=>'Dresses',
                        '/pants-leggings-c-975'=>'Pants&Leggings',
                        '/jackets-c-947'=>'Jackets',
                        '/coats-c-953'=>'Coats',
                        '/swimwear-beachwear-c-178'=>'Swimwear&Beachwear',
                        '/rompers-jumpsuits-c-970'=>'Rompers&Jumpsuits',
                        '/jeans-c-49'=>'Jeans',
                        '/clothing-tops-c-621'=>'Tops',
                        '/shorts-c-51'=>'Shorts',
                        '/skirt-c-99'=>'Skirts',
                        '/sweaters-knits-c-961'=>'Sweaters&Knits',
                        '/clothing-c-615'=>'View All Clothing',
                        '/suits-co-ords-c-1002'=>'Suits & Co-ords',

                    ),
                ),
                //分类导航链接3
                'third' => array(
                    'title1' => 'SHOES',
                    'title_link' => '/shoes-c-53',
                    'title2' => 'SHOP BY CATEGORY',
                    'content' => array(
                        '/flats-c-152'=>'Flats',
                        '/sandals-c-150'=>'Sandals',
                        '/platforms-c-151'=>'Platforms',
                        '/lace-up-shoes-c-1007'=>'Lace Up Shoes',
                        '/heels-c-636'=>'Heels',
                        '/boots-c-149'=>'Boots',
                        '/sports-shoes-c-1008'=>'Sports Shoes',
                        '/shoes-c-53'=>'View All Shoes',
                    ),
                ),
                //分类导航链接4
                'fourth' => array(
                    'title1' => 'ACCESSORIES',
                    'title_link' => '/accessory-c-52',
                    'title2' => 'SHOP BY CATEGORY',
                    'content' => array(
                        '/bags-wallets-c-1016'=>'Bags & Wallets',
                        '/hats-c-1018'=>'Hats',
                        '/jewellery-c-638'=>'Jewelry',
                        '/sunglasses-c-58'=>'Sunglasses',
                        '/scarves-snoods-c-57'=>'Scarves',
                        '/gloves-c-645'=>'Gloves',
                        '/socks-tights-c-54'=>'Socks & Tights',
                        '/hair-accessories-c-67'=>'Hair Accessories',
                        '/belts-c-59'=>'Belts',
                        '/accessory-c-52'=>'View All Accessories',
                        '/home-decor-c-795'=>'Home Decor',
//                        '/beauty-c-1019'=>'Beauty',


                    ),
                ),
                //分类导航链接5
                'fifth' => array(
                    'title1' => 'THE CHOIES GALAXY',
                    'title_link' => '',
                    'title2' => '',
                    'content' => array(
                        '/ballerina-sportsluxe-edit-c-1006' => 'Ballerina Sportsluxe',
                        '/music-festivals-edit-c-1020' => 'Music Festivals',
                        '/boho-chic-c-1024' => 'Boho Chic',
                        '/90-s-school-style-c-1022' => "90's School Style",
                        '/90-s-minimal-style-c-1023' => "90's Minimal Style",
                        '/denim-style-in-c-719' => 'Denim',
                    ),
                ),
                'sixth' => array(
                    'title1' => 'SALE',
                    'title_link' => '/outlet-c-101',
                    'title2' => '',
                    'content' => array(
                        '/only-9-c-1170' => 'Only $9.90',
                        '/only-19-c-1171' => 'Only $19.90',
                        '/only-29-c-1172' => 'Only $29.90',
                        '/outlet-c-101' => 'Outlet',
                        '/activity/flash_sale' => 'Flash Sale',
                        '/summer-clearance-c-451' => 'Summer Clearance',
                        ),
                ),
                'seventh' => array(
                    'title1' => 'TOP SELLERS',
                    'title_link' => '/choies-top-sellers-c-1188',
                    'title2' => '',
                    'content' => array(
                        '/top-seller-dresses-c-1189' => 'Top Seller: Dresses',
                        '/top-seller-blouses-and-shirts-c-1190' => 'Top Seller: Blouses & Shirts',
                        '/top-seller-coats-and-jackets-c-1191' => 'Top Seller: Coats & Jackets',
                        '/top-seller-sweater-and-knits-c-1192' => 'Top Seller: Sweater & Knits',
                        '/top-seller-skirts-c-1193' => 'Top Seller: Skirts',
                    ),
                ),
            ),
            'phone_content' =>array(
                //手机分类导航链接
                'phone_first' => 'CATEGORY',
                'phone_second' => 'My Account',
                'Go Back' => 'Go Back',
                //手机分类导航链接1
                'first' => array(
                    'title' => 'NEW IN',
                    'content' => array(
                        '/daily-new/week2' => 'This Week',
                        '/daily-new/week1' => 'Last Week',
                        '/daily-new/month' => 'Last Month',
                    ),
                ),
                //手机分类导航链接2
                'second' => array(
                    'title' => 'THE CHOIES GALAXY',
                    'content' => array(
                        '/ballerina-sportsluxe-edit-c-1006' => 'Ballerina Sportsluxe',
                        '/music-festivals-edit-c-1020' => 'Music Festivals',
                        '/boho-chic-c-1024' => 'Boho Chic',
                        '/90-s-school-style-c-1022' => "90's School Style",
                        '/90-s-minimal-style-c-1023' => "90's Minimal Style",
                        '/denim-style-in-c-719' => 'Denim',
                    ),
                ),
                //手机分类导航链接3
                'third' => array(
                    'title' => 'DRESSES',
                    'content' => array(
                        '/dresses-c-92' => 'View All',
                        '/backless-dress-c-456' => 'Backless Dresses',
                        '/black-dresses-c-203' => 'Black Dresses',
                        '/bodycon-dresses-c-211' => 'Bodycon Dresses',
                        '/floral-dresses-c-108' => 'Floral Dresses',
                        '/lace-dresses-c-209' => 'Lace Dresses',
                        '/maxi-dresses-c-207' => 'Maxi Dresses',
                        '/off-the-shoulder-dresses-c-504' => 'Off Shoulder Dresses',
                        '/party-dresses-c-205' => 'Party Dresses',
                        '/shift-dresses-c-724' => 'Shift Dresses',
                        '/shirt-dresses-c-725' => 'Shirt Dresses',
                        '/stripe-dresses-c-652' => 'Stripe Dresses',
                        '/white-dresses-c-204' => 'White Dresses',
                    ),
                ),
                'fourth' => array(
                    'title' => 'TOPS',
                    'content' => array(
                        "/t-shirts-c-245" => 'T-shirts',
                        "/blouses-shirts-c-616" => 'Blouses & Shirts',
                        "/bodysuits-c-250" => 'Bodysuits',
                        "/camis-tanks-c-617" =>'Camis & Tanks',
                        "/two-piece-suit-c-177" => 'CO-ORD Sets',
                        "/crop-tops-bralets-c-244" => 'Crop Tops & Bralets',
                        "/dress-tops-c-618" => 'Dress-tops',
                        "/kimonos-c-414" => 'Kimonos',
                        "/knitwear-sweaters-c-619" => 'Knitwear',
                        "/clothing-outerwear-c-623" => 'Outerwear',
                        "/one-pieces-c-626" => 'One-pieces',
                        "/swimwear-c-628" => 'Swimwear',
                    ),
                ),
                'fifth' => array(
                    'title' => 'BOTTOMS',
                    'content' => array(
                        "/bottoms-c-240" => 'View All',
                        "/jeans-c-49" => 'Jeans',
                        "/leggings-c-232" => 'Leggings',
                        "/skirt-c-99" =>'Skirts',
                        "/shorts-c-51" => 'Shorts',
                    ),
                ),
                'sixth' => array(
                    'title' => 'SHOES',
                    'content' => array(
                        "/shoes-c-53" => 'View All',
                        "/boots-c-149" => 'Boots',
                        "/sandals-c-150" => 'Sandals',
                        "/platforms-c-151" => 'Platforms',
                        "/flats-c-152" => 'Flats',
                        "/sneakers-athletic-shoes-c-635" => 'Sneakers & Athletic Shoes',
                        "/heels-c-636" => 'Heels',
                    ),
                ),
                'seventh' => array(
                    'title' => 'JEWELLERY',
                    'content' => array(
                        '/jewellery-c-638' => 'View All',
                        '/rings-c-62' => 'Rings',
                        '/earrings-c-63' => 'Earrings',
                        '/bracelets-bangles-c-640' => 'Bracelets & Bangles',
                        '/neck-c-639' => 'Neck',
                        '/anklets-c-650' => 'Anklets',
                        '/body-harness-c-705' => 'Body Harness',
                    ),
                ),
                'eighth' => array(
                    'title' => 'ACC&BAGS',
                    'content' => array(
                        '/accessories-bags-c-641' => 'View All',
                        '/bags-c-643' => 'Bags',
                        '/purses-c-644' => 'Purses',
                        '/gloves-c-645' => 'Gloves',
                        '/hats-caps-c-55' => 'Hats & Caps',
                        '/eye-masks-c-647' => 'Eye Masks',
                        '/scarves-snoods-c-57' => 'Scarves & Snoods',
                        '/socks-tights-c-54' => 'Socks & Tights',
                        '/sunglasses-c-58' => 'Sunglasses',
                        '/hair-accessories-c-67' => 'Hair Accessories',
                        '/hair-extensions-c-646' => 'Hair Extensions',
                        '/belts-c-59' => 'Belts',
                        '/home-decor-c-795' => 'Home Decor',
                        '/nails-c-460' => 'Nails',
                    ),
                ),
                'ninth' => array(
                    'title' => 'SALE',
                    'link' => '/outlet-c-101',
                ),

            ),
            'footer' => array(
                //底部输入框以及 WE ACCEPT
                'other' => array(
                    'first'=>'STAY IN THE KNOW',
                    'second'=>'Enter your email address to receive newsletter',
                    'third'=>'SIGN UP',
                    'fourth'=>'CHOIES SOCIAL',
                    'fifth'=>' WE ACCEPT',
                ),
                //底部链接组一
                'first' => array(
                    'first'=>'SHIPPING OPTIONS',
                    'second'=>'RETURNS',
                    'third'=>'SIZE GUIDE',
                    'fourth'=>'MEMBERSHIP',
                ),
                //底部链接组二
                'second' => array(
                    'title' => 'ABOUT US',
                    'content' => array(
                        '/about-us' => 'Who We Are',
                        '/affiliate-program' => 'Affiliates',
                        '/blogger/programme' => 'Bloggers',
                        '/Copyright-Infringement-Notice' => 'Copyright Notice',
                    ),
                ),
                'third' => array(
                    'title' => 'HELP',
                    'content' => array(
                        '/contact-us' => 'Contact Us',
                        '/faqs' => 'FAQs',
                        '/important-notice' => 'Notice Board',
                        '/how-to-order' => 'How to Order',
                    ),
                ),
                'fourth' => array(
                    'title' => 'SHOPPING GUIDE',
                    'content' => array(
                        '/payment' => 'Payments',
                        '/coupon-points' => 'Coupons',
                        '/brand/brandpage' => 'Brand List',
                        '/wholesale' => 'Wholesale',
                    ),
                ),

                'pc_footer' => array(
                    '© 2006-2016 CHOIES.COM' => '© 2006-2016 CHOIES.COM&nbsp;',
                    'PRIVACY POLICY' => 'PRIVACY POLICY',
                    'TERMS & CONDITIONS' => 'TERMS & CONDITIONS',
                ),

                'phone_footer' => array(
                    'BLOGGER' => 'BLOGGER',
                    '#LOOKBOOKS' => '#LOOKBOOKS',
                    'HERE' => 'HERE',
                    'Connect With Us' => 'Connect With Us',
                    'My Account' => 'My Account',
                    'Track Order' => 'Track Order',
                    'Order History' => 'Order History',
                    'About Us' => 'About Us',
                    'Membership' => 'Membership',
                    'Contact Us' => 'Contact Us',
                    'Copyright © 2006-2016 Choies.com' => 'Copyright © 2006-2016 Choies.com',
                    'Terms & Conditions' => 'Terms & Conditions',
                    'Privacy Policy' => 'Privacy Policy',
                ),
            ),
        ),
        'de'=>array(
            'lang' => array(
                'quick' =>'SCHNELLANSICHT',
                'addto' => 'Zur Wunschliste Hinzufügen',
                'onesize' => 'Eine Größe',
            ),
            'payment'=> array(
                'choosecard' =>'Bitte wählen Sie hier Kartentyp',
                'choosecard1' =>'Bitte wählen Sie Ihren Kreditkartentyp.',
            ),
            'customer' => array(
                'SIGN IN' => 'ANMELDEN',
                'choieser' => 'choieser',
                'My Order' => 'Bestellhistorie',
                'Track Order' => 'Verfolgen',
                'My Wishlist' => 'Meine Wunschliste',
                'My Profile' => 'Mein Profil',
                'Sign Out' => 'Abmelden',
            ),
            'bag'=> array(
                'ITEM' => '',
                'IN MY BAG' => 'Artikel in Ihrer Einkaufstasche',
                'VIEW BAG & CHECKOUT' => 'EINKAUFSTASCHE SEHEN',
            ),
            'pc_content' => array(
                'first' => array(
                    'title1' => 'NEUHEITEN',
                    'title_link' => '/daily-new/week2',
                    'title2' => 'SHOP BY',
                    'content' => array(
                        '/daily-new/week2' => 'Diese Woche',
                        '/daily-new/week1' => 'Letzte Woche',
                        '/daily-new/month' => 'Letzter Monat',
                    ),
                ),
                'second' => array(
                    'title1' => 'BEKLEIDUNG',
                    'title_link' => '/clothing-c-615',
                    'title2' => 'EINKAUF NACH KATEGORIE',
                    'content' => array(
                        '/dresses-c-92'=>'Kleider',
                        '/pants-leggings-c-975'=>'Hosen & Leggings',
                        '/jackets-c-947'=>'Jacken',
                        '/coats-c-953'=>'Mäntel & Jacken',
                        '/swimwear-beachwear-c-178'=>'Bademode',
                        '/rompers-jumpsuits-c-970'=>'Jumpsuits & Overalls',
                        '/jeans-c-49'=>'Jeans',
                        '/clothing-tops-c-621'=>'Tops',
                        '/shorts-c-51'=>'Shorts',
                        '/skirt-c-99'=>'Röcke',
                        '/sweaters-knits-c-961'=>'Pullover & Strickjacken',
                        '/clothing-c-615'=>'Alle Bekleidung',
                        '/suits-co-ords-c-1002'=>'Anzüge & Koordinaten-Sets',

                    ),
                ),
                'third' => array(
                    'title1' => 'SCHUHE',
                    'title_link' => '/shoes-c-53',
                    'title2' => 'EINKAUF NACH KATEGORIE',
                    'content' => array(
                        '/flats-c-152'=>'Ebeneschuhe',
                        '/sandals-c-150'=>'Sandalen',
                        '/platforms-c-151'=>'Plateauschuhe',
                        '/lace-up-shoes-c-1007'=>'Schnürschuhe',
                        '/heels-c-636'=>'Absatzschuhe',
                        '/boots-c-149'=>'Stiefeln',
                        '/sports-shoes-c-1008'=>'Sportschuhe',
                        '/shoes-c-53'=>'Alle Schuhe',
                    ),
                ),
                'fourth' => array(
                    'title1' => 'ACCESSOIRES',
                    'title_link' => '/accessory-c-52',
                    'title2' => 'EINKAUF NACH KATEGORIE',
                    'content' => array(
                        '/bags-wallets-c-1016'=>'Bags & Wallets',
                        '/hats-c-1018'=>'Hats',
                        '/jewellery-c-638'=>'Schmuck',
                        '/sunglasses-c-58'=>'Sonnenbrillen',
                        '/scarves-snoods-c-57'=>'Schals',
                        '/gloves-c-645'=>'Handschuhe',
                        '/socks-tights-c-54'=>'Socken & Strümpfe',
                        '/hair-accessories-c-67'=>'Haarschmuck',
                        '/belts-c-59'=>'Gürtel',
                        '/accessory-c-52'=>'Alle Accessoires',
                        '/home-decor-c-795'=>'Innendekoration',
//                        '/beauty-c-1019'=>'Beauty',


                    ),
                ),
                'fifth' => array(
                    'title1' => 'GALAXIE VON CHOIES',
                    'title_link' => '',
                    'title2' => '',
                    'content' => array(
                        '/ballerina-sportsluxe-edit-c-1006' => 'Sports-Ballerina‎ Luxusdesign',
                        '/music-festivals-edit-c-1020' => 'Musikfestivals',
                        '/boho-chic-c-1024' => 'Boho Chic',
                        '/90-s-school-style-c-1022' => "Schulmode der 90er",
                        '/90-s-minimal-style-c-1023' => "Minimal-Stil der 90er",
                        '/denim-style-in-c-719' => 'Jeans Stil',
                    ),
                ),
                'sixth' => array(
                    'title1' => 'SALE',
                    'title_link' => '/outlet-c-101',
                    'title2' => '',
                    'content' => array(
                        '/only-9-c-1170' => 'Only $9.90',
                        '/only-19-c-1171' => 'Only $19.90',
                        '/only-29-c-1172' => 'Only $29.90',
                        '/outlet-c-101' => 'Outlet',
                        '/activity/flash_sale' => 'Flash Sale',
                        '/summer-clearance-c-451' => 'Summer Clearance',
                    ),
                ),
                'seventh' => array(
                    'title1' => 'TOP SELLERS',
                    'title_link' => '/choies-top-sellers-c-1188',
                    'title2' => '',
                    'content' => array(
                        '/top-seller-dresses-c-1189' => 'Top Seller: Dresses',
                        '/top-seller-blouses-and-shirts-c-1190' => 'Top Seller: Blouses & Shirts',
                        '/top-seller-coats-and-jackets-c-1191' => 'Top Seller: Coats & Jackets',
                        '/top-seller-sweater-and-knits-c-1192' => 'Top Seller: Sweater & Knits',
                        '/top-seller-skirts-c-1193' => 'Top Seller: Skirts',
                    ),
                ),
            ),
            'phone_content' =>array(
                'phone_first' => 'CATEGORY',
                'phone_second' => 'My Account',
                'Go Back' => 'Go Back',
                'first' => array(
                    'title' => 'NEUHEITEN',
                    'content' => array(
                        '/daily-new/week2' => 'Diese Woche',
                        '/daily-new/week1' => 'Letzte Woche',
                        '/daily-new/month' => 'Letzter Monat',
                    ),
                ),
                'second' => array(
                    'title' => 'GALAXIE VON CHOIES',
                    'content' => array(
                        '/ballerina-sportsluxe-edit-c-1006' => 'Sports-Ballerina‎ Luxusdesign',
                        '/music-festivals-edit-c-1020' => 'Musikfestivals',
                        '/boho-chic-c-1024' => 'Boho Chic',
                        '/90-s-school-style-c-1022' => "Schulmode der 90er",
                        '/90-s-minimal-style-c-1023' => "Minimal-Stil der 90er",
                        '/denim-style-in-c-719' => 'Jeans Stil',
                    ),
                ),
                'third' => array(
                    'title' => 'KLEIDER',
                    'content' => array(
                        '/dresses-c-92' => 'Alle anzeigen',
                        '/backless-dress-c-456' => 'Rückenfreie Kleider',
                        '/black-dresses-c-203' => 'Schwarze Kleider',
                        '/bodycon-dresses-c-211' => 'Figurbetonte Kleider',
                        '/floral-dresses-c-108' => 'Blumen Kleider',
                        '/lace-dresses-c-209' => 'Spitzenkleider',
                        '/maxi-dresses-c-207' => 'Maxikleider',
                        '/off-the-shoulder-dresses-c-504' => 'Schulterfreie Kleider',
                        '/party-dresses-c-205' => 'Party Kleider',
                        '/shift-dresses-c-724' => 'Etuikleider',
                        '/shirt-dresses-c-725' => 'Hemdkleider',
                        '/stripe-dresses-c-652' => 'Streifen Kleider',
                        '/white-dresses-c-204' => 'Weiße Kleider',
                    ),
                ),
                'fourth' => array(
                    'title' => 'OBERTEILE',
                    'content' => array(
                        "/t-shirts-c-245" => 'T-shirts',
                        "/blouses-shirts-c-616" => 'Hemden & Blusen',
                        "/bodysuits-c-250" => 'Bodysuits',
                        "/camis-tanks-c-617" =>'Trägertops & Tank-Tops',
                        "/two-piece-suit-c-177" => 'Koordinaten-Sets',
                        "/crop-tops-bralets-c-244" => '',
                        "/dress-tops-c-618" => 'Kleid Tops',
                        "/kimonos-c-414" => 'Kimonos',
                        "/knitwear-sweaters-c-619" => 'Strickwaren',
                        "/clothing-outerwear-c-623" => 'Oberbekleidung',
                        "/one-pieces-c-626" => 'Ein-Stück',
                        "/swimwear-c-628" => 'Bademode',
                    ),
                ),
                'fifth' => array(
                    'title' => 'UNTERTEILE',
                    'content' => array(
                        "/bottoms-c-240" => 'Alle anzeigen',
                        "/jeans-c-49" => 'Jeans',
                        "/leggings-c-232" => 'Leggings',
                        "/skirt-c-99" =>'Röcke',
                        "/shorts-c-51" => 'Shorts',
                    ),
                ),
                'sixth' => array(
                    'title' => 'SHOES',
                    'content' => array(
                        "/shoes-c-53" => 'Alle Schuhe',
                        "/boots-c-149" => 'Stiefeln',
                        "/sandals-c-150" => 'Sandalen',
                        "/platforms-c-151" => 'Plateauschuhe',
                        "/flats-c-152" => 'Ebeneschuhe',
                        "/sneakers-athletic-shoes-c-635" => 'Sneakers & Athletic Shoes',
                        "/heels-c-636" => 'Absatzschuhe',
                    ),
                ),
                'seventh' => array(
                    'title' => 'SCHMUCK',
                    'content' => array(
                        '/jewellery-c-638' => 'Alle anzeigen',
                        '/rings-c-62' => 'Ringe',
                        '/earrings-c-63' => 'Ohrringe',
                        '/bracelets-bangles-c-640' => 'Armbänder & Armreifen',
                        '/neck-c-639' => 'Halsschmuckn',
                        '/anklets-c-650' => 'Fußkettchen',
                        '/body-harness-c-705' => 'Körper Auffanggurt',
                    ),
                ),
                'eighth' => array(
                    'title' => 'ACC&TASCHEN',
                    'content' => array(
                        '/accessories-bags-c-641' => 'Alle anzeigen',
                        '/bags-c-643' => 'Taschen',
                        '/purses-c-644' => 'Geldbörsen',
                        '/gloves-c-645' => 'Handschuhe',
                        '/hats-caps-c-55' => 'Hüte und Mützen',
                        '/eye-masks-c-647' => 'Augenmaske',
                        '/scarves-snoods-c-57' => 'Schals & Schlauchschals',
                        '/socks-tights-c-54' => 'Socken & Strumpfhosen',
                        '/sunglasses-c-58' => 'Sonnenbrillen',
                        '/hair-accessories-c-67' => 'Haarschmuck',
                        '/hair-extensions-c-646' => 'Perücke',
                        '/belts-c-59' => 'Gürtel',
                        '/home-decor-c-795' => 'Innendekoration',
                        '/nails-c-460' => 'Nagellack',
                    ),
                ),
                'ninth' => array(
                    'title' => 'SALE',
                    'link' => '/outlet-c-101',
                ),

            ),
            'footer' => array(
                'other' => array(
                    'first'=>'BLEIBEN SIE INFORMIERT',
                    'second'=>'Geben Sie Ihre E-Mail-Adresse hier ein, um Newsletter zu erhalten',
                    'third'=> 'ANMELDEN',
                    'fourth'=>'SOZIALE NETZWERKE',
                    'fifth'=>'WIR AKZEPTIEREN',
                ),
                'first' => array(
                    'first'=>'VERSANDARTEN',
                    'second'=>'RÜCKGABE',
                    'third'=>'GRÖSSENTABELLE',
                    'fourth'=>'MITGLIEDSCHAFT',
                ),
                'second' => array(
                    'title' => 'ÜBER UNS',
                    'content' => array(
                        '/about-us' => 'Wer wir sind',
                        '/affiliate-program' => 'Partnerprogramm',
                        '/blogger/programme' => 'Bloggers',
                        '/Copyright-Infringement-Notice' => 'Copyright Notice',
                    ),
                ),
                'third' => array(
                    'title' => 'HILFE',
                    'content' => array(
                        '/contact-us' => 'Kontakt',
                        '/faqs' => 'FAQs',
                        '/important-notice' => 'Hinweise',
                        '/how-to-order' => 'Wie man bestellt',
                    ),
                ),
                'fourth' => array(
                    'title' => 'EINKAUFSFÜHRER',
                    'content' => array(
                        '/payment' => 'Bezahlung',
                        '/coupon-points' => 'Gutscheine',
                        '/brand/brandpage' => 'Brand List',
                        '/wholesale' => 'Großhandel',
                    ),
                ),

                'pc_footer' => array(
                    '© 2006-2016 CHOIES.COM' => '© 2006-2016 CHOIES.COM&nbsp;',
                    'PRIVACY POLICY' => 'DATENSCHUTZRICHTLINIE',
                    'TERMS & CONDITIONS' => 'AGB',
                ),

                'phone_footer' => array(
                    'BLOGGER' => 'BLOGGER',
                    '#LOOKBOOKS' => '#LOOKBOOKS',
                    'HERE' => 'HERE',
                    'Connect With Us' => 'Connect With Us',
                    'My Account' => 'MEIN KONTO',
                    'Track Order' => 'Verfolgen',
                    'Order History' => 'Bestellhistorie',
                    'About Us' => 'Über Choies',
                    'Membership' => 'Membership',
                    'Contact Us' => 'Kontakt',
                    'Copyright © 2006-2016 Choies.com' => 'Copyright © 2006-2016 Choies.com',
                    'Terms & Conditions' => 'AGB',
                    'Privacy Policy' => 'DATENSCHUTZRICHTLINIE',
                ),
            ),
        ),
        'es'=>array(
            'lang' => array(
                'quick' =>'VISTA RÁPIDA',
                'addto' => 'AÑADIR A SU LISTA DE DESEOS',
                'onesize' => 'talla única',
            ),
			'payment'=> array(
				'choosecard' =>'Por favor elige el tipo de tarjeta',
				'choosecard1' =>'Por favor elige el tipo de su tarjeta de crédito.',
			),
            'customer' => array(
                'REGISTER' => '',
                'SIGN IN' => 'ACCEDER',
                'choieser' => 'choieser',
                'My Order' => 'Mis Pedidos',
                'Track Order' => 'Rastrear',
                'My Wishlist' => 'Mi Lista de Deseos',
                'My Profile' => 'Mi Perfil',
                'Sign Out' => 'Salir',
            ),
            'bag'=> array(
                'ITEM' => 'artículo',
                'IN MY BAG' => '',
                'VIEW BAG & CHECKOUT' => 'VER MI BOLSA & PAGAR',
            ),
            'pc_content' => array(
                'first' => array(
                    'title1' => 'NOVEDADES',
                    'title_link' => '/daily-new/week2',
                    'title2' => 'SHOP BY',
                    'content' => array(
                        '/daily-new/week2' => 'Esta semana',
                        '/daily-new/week1' => 'La semana pasada',
                        '/daily-new/month' => 'El mes pasado',
                    ),
                ),
                'second' => array(
                    'title1' => 'ROPA',
                    'title_link' => '/clothing-c-615',
                    'title2' => 'COMPRAR POR CATÁLOGO',
                    'content' => array(
                        '/dresses-c-92'=>'Vestidos',
                        '/pants-leggings-c-975'=>'Pantalones y Leggins',
                        '/jackets-c-947'=>'Chaquetas',
                        '/coats-c-953'=>'Abrigos',
                        '/swimwear-beachwear-c-178'=>'Trajes de baño y Ropa de playa',
                        '/rompers-jumpsuits-c-970'=>'Monos crotos y Monos largos',
                        '/jeans-c-49'=>'Vaqueros',
                        '/clothing-tops-c-621'=>'Tops',
                        '/shorts-c-51'=>'Shorts',
                        '/skirt-c-99'=>'Faldas',
                        '/sweaters-knits-c-961'=>'Prendas de punto',
                        '/clothing-c-615'=>'Ver Todas Ropas',
                        '/suits-co-ords-c-1002'=>'Conjuntos',

                    ),
                ),
                'third' => array(
                    'title1' => 'ZAPATOS',
                    'title_link' => '/shoes-c-53',
                    'title2' => 'COMPRAR POR CATÁLOGO',
                    'content' => array(
                        '/flats-c-152'=>'Planos',
                        '/sandals-c-150'=>'Sandalias',
                        '/platforms-c-151'=>'Plataforma',
                        '/lace-up-shoes-c-1007'=>'Zapatos con cordónes',
                        '/heels-c-636'=>'Zapatos de tacón',
                        '/boots-c-149'=>'Botas',
                        '/sports-shoes-c-1008'=>'Zapatos deportivos',
                        '/shoes-c-53'=>'Ver Todos Zapatos',
                    ),
                ),
                'fourth' => array(
                    'title1' => 'ACCESORIOS',
                    'title_link' => '/accessory-c-52',
                    'title2' => 'COMPRAR POR CATÁLOGO',
                    'content' => array(
                        '/bags-wallets-c-1016'=>'Bags & Wallets',
                        '/hats-c-1018'=>'Faldas',
                        '/jewellery-c-638'=>'Joyas',
                        '/sunglasses-c-58'=>'Gafas de sol',
                        '/scarves-snoods-c-57'=>'Bufandas',
                        '/gloves-c-645'=>'Guantes',
                        '/socks-tights-c-54'=>'Calcetínes y Medias',
                        '/hair-accessories-c-67'=>'Accesorios para el pelo',
                        '/belts-c-59'=>'Cinturones',
                        '/accessory-c-52'=>'Ver Todos Accesarios',
                        '/home-decor-c-795'=>'Decoración del hogar',
//                        '/beauty-c-1019'=>'Belleza',


                    ),
                ),
                'fifth' => array(
                    'title1' => 'GALAXIA DE CHOIES',
                    'title_link' => '',
                    'title2' => '',
                    'content' => array(
                        '/ballerina-sportsluxe-edit-c-1006' => '',
                        '/music-festivals-edit-c-1020' => 'Fiesta de la música',
                        '/boho-chic-c-1024' => 'Estilo boho chic',
                        '/90-s-school-style-c-1022' => "Estilo de la escuela de los 90's",
                        '/90-s-minimal-style-c-1023' => "Tendencia minimalista de los 90's",
                        '/denim-style-in-c-719' => 'Denim',
                    ),
                ),
                'sixth' => array(
                    'title1' => 'REBAJAS',
                    'title_link' => '/outlet-c-101',
                    'title2' => '',
                    'content' => array(
                        '/only-9-c-1170' => 'Sólo $9.90',
                        '/only-19-c-1171' => 'Sólo $19.90',
                        '/only-29-c-1172' => 'Sólo $29.90',
                        '/outlet-c-101' => 'Outlet',
                        '/activity/flash_sale' => 'Flash Sale',
                        '/summer-clearance-c-451' => 'Liquidación Verano',
                    ),
                ),
                'seventh' => array(
                    'title1' => 'MEJORES VENDIDOS',
                    'title_link' => '/choies-top-sellers-c-1188',
                    'title2' => '',
                    'content' => array(
                        '/top-seller-dresses-c-1189' => 'Mejor Vendido: Vestidos',
                        '/top-seller-blouses-and-shirts-c-1190' => 'Mejor Vendido: Blusas  & Camisas',
                        '/top-seller-coats-and-jackets-c-1191' => 'Mejor Vendido: Abrigos & Chaquetas',
                        '/top-seller-sweater-and-knits-c-1192' => 'Mejor Vendido: Suéter & Tejidos ',
                        '/top-seller-skirts-c-1193' => 'Mejor Vendido: Faldas',
                    ),
                ),
            ),
            'phone_content' =>array(
                'phone_first' => 'CATEGORÍA',
                'phone_second' => 'Mi Cuenta',
                'Go Back' => 'Volver',
                'first' => array(
                    'title' => 'NOVEDADES',
                    'content' => array(
                        '/daily-new/week2' => 'Esta semana',
                        '/daily-new/week1' => 'La semana pasada',
                        '/daily-new/month' => 'El mes pasado',
                    ),
                ),
                'second' => array(
                    'title' => 'THE CHOIES GALAXY',
                    'content' => array(
                        '/ballerina-sportsluxe-edit-c-1006' => '',
                        '/music-festivals-edit-c-1020' => 'Fiesta de la música',
                        '/boho-chic-c-1024' => 'Estilo boho chic',
                        '/90-s-school-style-c-1022' => "Estilo de la escuela de los 90's",
                        '/90-s-minimal-style-c-1023' => "Tendencia minimalista de los 90's",
                        '/denim-style-in-c-719' => 'Denim',
                    ),
                ),
                'third' => array(
                    'title' => 'VESTIDOS',
                    'content' => array(
                        '/dresses-c-92' => 'Ver todos',
                        '/backless-dress-c-456' => 'Vestidos sin Espalda',
                        '/black-dresses-c-203' => 'Vestidos Negros',
                        '/bodycon-dresses-c-211' => 'Vestidos Ajustados',
                        '/floral-dresses-c-108' => 'Vestidos Florales',
                        '/lace-dresses-c-209' => 'Vestidos de Encaje',
                        '/maxi-dresses-c-207' => 'Vestidos Largos',
                        '/off-the-shoulder-dresses-c-504' => 'Vestidos al Aire',
                        '/party-dresses-c-205' => 'Vestidos de Fiesta',
                        '/shift-dresses-c-724' => 'Vestidos Sueltos',
                        '/shirt-dresses-c-725' => 'Vestidos Camiseros',
                        '/stripe-dresses-c-652' => 'Vestidos a Rayas',
                        '/white-dresses-c-204' => 'Vestidos Blancos',
                    ),
                ),
                'fourth' => array(
                    'title' => 'TOPS',
                    'content' => array(
                        "/t-shirts-c-245" => 'Camisetas',
                        "/blouses-shirts-c-616" => 'Blusas & Camisas',
                        "/bodysuits-c-250" => 'Body',
                        "/camis-tanks-c-617" =>'Camisola & Chaleco',
                        "/two-piece-suit-c-177" => 'Conjuntos',
                        "/crop-tops-bralets-c-244" => 'Tops Cortos',
                        "/dress-tops-c-618" => 'Tops Largos',
                        "/kimonos-c-414" => 'Kimonos',
                        "/knitwear-sweaters-c-619" => 'Prendas de Punto',
                        "/clothing-outerwear-c-623" => 'Prendas Exteriores',
                        "/one-pieces-c-626" => 'Prendas de una Pieza',
                        "/swimwear-c-628" => 'Bañadores',
                    ),
                ),
                'fifth' => array(
                    'title' => 'PARTES DE ABAJO',
                    'content' => array(
                        "/bottoms-c-240" => 'Ver todos',
                        "/jeans-c-49" => 'Vaqueros',
                        "/leggings-c-232" => 'Leggings',
                        "/skirt-c-99" =>'Faldas',
                        "/shorts-c-51" => 'Shorts',
                    ),
                ),
                'sixth' => array(
                    'title' => 'ZAPATOS',
                    'content' => array(
                        "/shoes-c-53" => 'Todos zapatos',
                        "/boots-c-149" => 'Botas',
                        "/sandals-c-150" => 'Sandalias',
                        "/platforms-c-151" => 'Plataforma',
                        "/flats-c-152" => 'Planos',
                        "/sneakers-athletic-shoes-c-635" => 'Sneakers & Athletic Shoes',
                        "/heels-c-636" => 'Zapatos de tacón',
                    ),
                ),
                'seventh' => array(
                    'title' => 'JOYAS',
                    'content' => array(
                        '/jewellery-c-638' => 'Ver todos',
                        '/rings-c-62' => 'Anillos',
                        '/earrings-c-63' => 'Pendientes',
                        '/bracelets-bangles-c-640' => 'Pulseras',
                        '/neck-c-639' => 'Collares',
                        '/anklets-c-650' => 'Pulseras de Tobillo',
                        '/body-harness-c-705' => 'Accesorio para Cuerpo',
                    ),
                ),
                'eighth' => array(
                    'title' => 'ACCESORIOS & BOLSOS',
                    'content' => array(
                        '/accessories-bags-c-641' => 'Ver todos',
                        '/bags-c-643' => 'Bolsos',
                        '/purses-c-644' => 'Monederos',
                        '/gloves-c-645' => 'Guantes',
                        '/hats-caps-c-55' => 'Sombreros & Gorros',
                        '/eye-masks-c-647' => 'Máscaras de Ojos',
                        '/scarves-snoods-c-57' => 'Bufandas & Cuello Snoods',
                        '/socks-tights-c-54' => 'Calcetínes & Medias',
                        '/sunglasses-c-58' => 'Gafas del Sol',
                        '/hair-accessories-c-67' => 'Joyas para el Pelo',
                        '/hair-extensions-c-646' => 'Pelucas',
                        '/belts-c-59' => 'Cinturóns',
                        '/home-decor-c-795' => 'Decoración del Holgar',
                        '/nails-c-460' => 'Esmalte de uñas',
                    ),
                ),
                'ninth' => array(
                    'title' => 'SALE',
                    'link' => '/outlet-c-101',
                ),

            ),
            'footer' => array(
                'other' => array(
                    'first'=>'ENTÉRATE DE TODO',
                    'second'=>'Introduzca su dirección de correo electrónico para recibir las noticias',
                    'third'=>' SUSCRIBIRSE',
                    'fourth'=>' REDES SOCIALES',
                    'fifth'=>' ACEPTAMOS',
                ),
                'first' => array(
                    'first'=>'OPCIONES DE ENVÍOS',
                    'second'=>'DEVOLUCIONES',
                    'third'=>'GUÍA DE TALLA',
                    'fourth'=>'SOCIOS',
                ),
                'second' => array(
                    'title' => 'Soobre nosotrs',
                    'content' => array(
                        '/about-us' => 'Quiénes somos',
                        '/affiliate-program' => 'Afiliados',
                        '/blogger/programme' => 'Bloggers',
                        '/Copyright-Infringement-Notice' => 'Aviso de Copyright',
                    ),
                ),
                'third' => array(
                    'title' => 'Ayuda',
                    'content' => array(
                        '/contact-us' => 'Contáctenos',
                        '/faqs' => 'FAQs',
                        '/important-notice' => 'Tablón de anuncios',
                        '/how-to-order' => 'Como realizar un pedido',
                    ),
                ),
                'fourth' => array(
                    'title' => 'Guía de compras',
                    'content' => array(
                        '/payment' => 'Pago',
                        '/coupon-points' => 'Cupones',
                        '/brand/brandpage' => 'Lista de Marca',
                        '/wholesale' => 'Venta al por mayor',
                    ),
                ),

                'pc_footer' => array(
                    '© 2006-2016 CHOIES.COM' => '© 2006-2016 CHOIES.COM&nbsp;',
                    'PRIVACY POLICY' => 'POLÍTICA DE PRIVACIDAD',
                    'TERMS & CONDITIONS' => 'TÉRMINOS Y CONDICIONES',
                ),

                'phone_footer' => array(
                    'BLOGGER' => 'Blogger de Moda',
                    '#LOOKBOOKS' => '#LOOKBOOKS',
                    'HERE' => '',
                    'Connect With Us' => 'CONTÁCTENOS',
                    'My Account' => 'MI CUENTA',
                    'Track Order' => 'Rastrear',
                    'Order History' => 'Mis Puntos',
                    'About Us' => 'Sobre Nosotros',
                    'Membership' => 'Socios',
                    'Contact Us' => 'Contáctenos',
                    'Copyright © 2006-2016 Choies.com' => 'Copyright © 2006-2016 Choies.com',
                    'Terms & Conditions' => 'Términos & Condiciones',
                    'Privacy Policy' => 'Política de privacidad',
                ),
            ),

        ),
        'fr'=>array(
            'lang' => array(
                'quick' =>'VUE RAPIDE',
                'addto' => "Ajouter à la liste d'envies",
                'onesize' => 'taille unique',
            ),
			'payment'=> array(
				'choosecard' =>'Veuillez choisir le type de carte',
				'choosecard1' =>'Veuillez choisir le type de carte de crédit.',
			),
            'customer' => array(
                'REGISTER' => '',
                'SIGN IN' => "S'INSCRIRE",
                'choieser' => 'choieser',
                'My Order' => 'Mes commandes',
                'Track Order' => 'Suivi de Commande',
                'My Wishlist' => "Ma Liste d'Envies",
                'My Profile' => 'Mon profil',
                'Sign Out' => 'Me Déconnecter',
            ),
            'bag'=> array(
                'ITEM' => 'article',
                'IN MY BAG' => 'dans votre panier',
                'VIEW BAG & CHECKOUT' => 'VOIR MON PANIER & PAIEMENT',
            ),
            'pc_content' => array(
                'first' => array(
                    'title1' => 'NOUVEAU',
                    'title_link' => '/daily-new/week2',
                    'title2' => 'PRODUITS PAR',
                    'content' => array(
                        '/daily-new/week2' => 'Cette semaine',
                        '/daily-new/week1' => 'La semaine dernière',
                        '/daily-new/month' => 'Le mois dernier',
                    ),
                ),
                'second' => array(
                    'title1' => 'VÊTEMENTS',
                    'title_link' => '/clothing-c-615',
                    'title2' => 'PRODUITS PAR CATÉGORIE',
                    'content' => array(
                        '/dresses-c-92'=>'Robes',
                        '/pants-leggings-c-975'=>'Pantalons & Leggings',
                        '/jackets-c-947'=>'Blousons',
                        '/coats-c-953'=>'Manteaux',
                        '/swimwear-beachwear-c-178'=>'Maillots de bain',
                        '/rompers-jumpsuits-c-970'=>'Combinaisons',
                        '/jeans-c-49'=>'Jeans',
                        '/clothing-tops-c-621'=>'Tops',
                        '/shorts-c-51'=>'Shorts',
                        '/skirt-c-99'=>'Jupes',
                        '/sweaters-knits-c-961'=>'Pulls & Tricots',
                        '/clothing-c-615'=>'Tous les vêtements',
                        '/suits-co-ords-c-1002'=>'Ensemble',

                    ),
                ),
                'third' => array(
                    'title1' => 'CHAUSSURES',
                    'title_link' => '/shoes-c-53',
                    'title2' => 'PRODUITS PAR CATÉGORIE',
                    'content' => array(
                        '/flats-c-152'=>'Chaussure plates',
                        '/sandals-c-150'=>'Sandales',
                        '/platforms-c-151'=>'Platformes',
                        '/lace-up-shoes-c-1007'=>'Chaussures à lacets',
                        '/heels-c-636'=>'Talons',
                        '/boots-c-149'=>'Bottes',
                        '/sports-shoes-c-1008'=>'Chaussures de sport',
                        '/shoes-c-53'=>'Toutes les chaussures',
                    ),
                ),
                'fourth' => array(
                    'title1' => 'ACCESSORIES',
                    'title_link' => '/accessory-c-52',
                    'title2' => 'PRODUITS PAR CATÉGORIE',
                    'content' => array(
                        '/bags-wallets-c-1016'=>'Bags & Wallets',
                        '/hats-c-1018'=>'Hats',
                        '/jewellery-c-638'=>'Bijoux',
                        '/sunglasses-c-58'=>'Lunettes de soleil',
                        '/scarves-snoods-c-57'=>'Echarpes',
                        '/gloves-c-645'=>'Gants',
                        '/socks-tights-c-54'=>'Chaussettes & Collants',
                        '/hair-accessories-c-67'=>'Accessoires pour cheveux',
                        '/belts-c-59'=>'Ceintures',
                        '/accessory-c-52'=>'Tous les accessoires',
                        '/home-decor-c-795'=>'Décoration intérieure',
//                        '/beauty-c-1019'=>'Beauté',


                    ),
                ),
                'fifth' => array(
                    'title1' => 'LA GALAXIE DE CHOIES',
                    'title_link' => '',
                    'title2' => '',
                    'content' => array(
                        '/ballerina-sportsluxe-edit-c-1006' => 'Ballerine sport de luxe',
                        '/music-festivals-edit-c-1020' => 'Festival de musique',
                        '/boho-chic-c-1024' => 'Bohème chic',
                        '/90-s-school-style-c-1022' => "Style de campus des années 90",
                        '/90-s-minimal-style-c-1023' => "Style minimal des années 90",
                        '/denim-style-in-c-719' => 'Jean',
                    ),
                ),
                'sixth' => array(
                    'title1' => 'Vente',
                    'title_link' => '/outlet-c-101',
                    'title2' => '',
                    'content' => array(
                        '/only-9-c-1170' => 'Only $9.90',
                        '/only-19-c-1171' => 'Only $19.90',
                        '/only-29-c-1172' => 'Only $29.90',
                        '/outlet-c-101' => 'Outlet',
                        '/activity/flash_sale' => 'Flash Sale',
                        '/summer-clearance-c-451' => 'Summer Clearance',
                    ),
                ),
                'seventh' => array(
                    'title1' => 'TOP SELLERS',
                    'title_link' => '/choies-top-sellers-c-1188',
                    'title2' => '',
                    'content' => array(
                        '/top-seller-dresses-c-1189' => 'Top Seller: Dresses',
                        '/top-seller-blouses-and-shirts-c-1190' => 'Top Seller: Blouses & Shirts',
                        '/top-seller-coats-and-jackets-c-1191' => 'Top Seller: Coats & Jackets',
                        '/top-seller-sweater-and-knits-c-1192' => 'Top Seller: Sweater & Knits',
                        '/top-seller-skirts-c-1193' => 'Top Seller: Skirts',
                    ),
                ),
            ),
            'phone_content' =>array(
                'phone_first' => 'CATÉGORIE',
                'phone_second' => 'Mon Compte',
                'Go Back' => 'Retourner',
                'first' => array(
                    'title' => 'NOUVEAUTÉS',
                    'content' => array(
                        '/daily-new/week2' => 'Cette semaine',
                        '/daily-new/week1' => 'La semaine dernière',
                        '/daily-new/month' => 'Le mois dernier',
                    ),
                ),
                'second' => array(
                    'title' => 'LA GALAXIE DE CHOIES',
                    'content' => array(
                        '/ballerina-sportsluxe-edit-c-1006' => 'Ballerine sport de luxe',
                        '/music-festivals-edit-c-1020' => 'Festival de musique',
                        '/boho-chic-c-1024' => 'Bohème chic',
                        '/90-s-school-style-c-1022' => "Style de campus des années 90",
                        '/90-s-minimal-style-c-1023' => "Style minimal des années 90",
                        '/denim-style-in-c-719' => 'Jean',
                    ),
                ),
                'third' => array(
                    'title' => 'ROBES',
                    'content' => array(
                        '/dresses-c-92' => 'Voir tout',
                        '/backless-dress-c-456' => 'Robes Dos Nu',
                        '/black-dresses-c-203' => 'Robes Noires',
                        '/bodycon-dresses-c-211' => 'Robes Moulants',
                        '/floral-dresses-c-108' => 'Robes Floraux',
                        '/lace-dresses-c-209' => 'Robes Dentelles',
                        '/maxi-dresses-c-207' => 'Maxi Robes',
                        '/off-the-shoulder-dresses-c-504' => 'Robes Épaules Dénudées',
                        '/party-dresses-c-205' => 'Robes de Soirée',
                        '/shift-dresses-c-724' => 'Robes Droites',
                        '/shirt-dresses-c-725' => 'Robes Chemisiers',
                        '/stripe-dresses-c-652' => 'Robes Rayures',
                        '/white-dresses-c-204' => 'Robes Blanches',
                    ),
                ),
                'fourth' => array(
                    'title' => 'TOPS',
                    'content' => array(
                        "/t-shirts-c-245" => 'T-shirts',
                        "/blouses-shirts-c-616" => 'Blouses & Chemises',
                        "/bodysuits-c-250" => 'Body',
                        "/camis-tanks-c-617" =>'Camisoles et Débardeurs',
                        "/two-piece-suit-c-177" => 'Ensemble coordonné',
                        "/crop-tops-bralets-c-244" => 'Tops',
                        "/dress-tops-c-618" => 'Robes-tops',
                        "/kimonos-c-414" => 'Kimonos',
                        "/knitwear-sweaters-c-619" => 'Tricots',
                        "/clothing-outerwear-c-623" => 'Manteaux',
                        "/one-pieces-c-626" => 'Une-Pièces',
                        "/swimwear-c-628" => 'Maillot de Bain',
                    ),
                ),
                'fifth' => array(
                    'title' => 'BOTTOMS',
                    'content' => array(
                        "/bottoms-c-240" => 'Voir tout',
                        "/jeans-c-49" => 'Jeans',
                        "/leggings-c-232" => 'Leggings',
                        "/skirt-c-99" =>'Jupes',
                        "/shorts-c-51" => 'Short',
                    ),
                ),
                'sixth' => array(
                    'title' => 'CHAUSSURES',
                    'content' => array(
                        "/shoes-c-53" => 'Toutes les chaussures',
                        "/boots-c-149" => 'Bottes',
                        "/sandals-c-150" => 'Sandales',
                        "/platforms-c-151" => 'Platformes',
                        "/flats-c-152" => 'Chaussure plates',
                        "/sneakers-athletic-shoes-c-635" => 'Sneakers & Athletic Shoes',
                        "/heels-c-636" => 'Talons',
                    ),
                ),
                'seventh' => array(
                    'title' => 'JEWELLERY',
                    'content' => array(
                        '/jewellery-c-638' => 'Voir tout',
                        '/rings-c-62' => 'Bagues',
                        '/earrings-c-63' => 'Boucles d‘Oreilles',
                        '/bracelets-bangles-c-640' => 'Bracelets',
                        '/neck-c-639' => 'Colliers',
                        '/anklets-c-650' => 'Bracelets de cheville',
                        '/body-harness-c-705' => 'Harnais de corps',
                    ),
                ),
                'eighth' => array(
                    'title' => 'ACC&SACS',
                    'content' => array(
                        '/accessories-bags-c-641' => 'Voir tout',
                        '/bags-c-643' => 'Sacs',
                        '/purses-c-644' => 'Porte-monnais',
                        '/gloves-c-645' => 'Gants',
                        '/hats-caps-c-55' => 'Chapeaux & Casquettes',
                        '/eye-masks-c-647' => 'Masques pour les yeux',
                        '/scarves-snoods-c-57' => 'Echarpes & Foulards',
                        '/socks-tights-c-54' => 'Chaussettes & Collants',
                        '/sunglasses-c-58' => 'Lunettes de soleil',
                        '/hair-accessories-c-67' => 'Accessoires de cheveux',
                        '/hair-extensions-c-646' => 'Rallonges de cheveux',
                        '/belts-c-59' => 'Ceintures',
                        '/home-decor-c-795' => 'Décoration de maison',
                        '/nails-c-460' => 'Vernis à ongles',
                    ),
                ),
                'ninth' => array(
                    'title' => 'VENTE',
                    'link' => '/outlet-c-101',
                ),

            ),
            'footer' => array(
                'other' => array(
                    'first'=>'RESTER DANS-LE-SAVOIR',
                    'second'=>'Entrez votre adresse email pour recevoir la newsletter',
                    'third'=>"S'INSCRIRE",
                    'fourth'=>'RÉSEAU SOCIAL',
                    'fifth'=>'Nous acceptons',
                ),
                'first' => array(
                    'first'=>"OPTIONS D'EXPÉDITION",
                    'second'=>'RETOURS',
                    'third'=>'GUIDE DES TAILLES',
                    'fourth'=>'ADHÉSION',
                ),
                'second' => array(
                    'title' => 'À PROPOS DE NOUS',
                    'content' => array(
                        '/about-us' => 'Qui nous sommes',
                        '/affiliate-program' => 'Filiales',
                        '/blogger/programme' => 'Bloggers',
                        '/Copyright-Infringement-Notice' => 'Avis de Copyright',
                    ),
                ),
                'third' => array(
                    'title' => 'AIDE',
                    'content' => array(
                        '/contact-us' => 'Contactez-Nous',
                        '/faqs' => 'FAQs',
                        '/important-notice' => "Tableau d'affichage",
                        '/how-to-order' => 'Comment commander',
                    ),
                ),
                'fourth' => array(
                    'title' => "GUIDE D'ACHAT",
                    'content' => array(
                        '/payment' => 'Paiements',
                        '/coupon-points' => 'Coupons',
                        '/brand/brandpage' => 'Liste de Marque',
                        '/wholesale' => 'Vente en gros',
                    ),
                ),

                'pc_footer' => array(
                    '© 2006-2016 CHOIES.COM' => '© 2006-2016 CHOIES.COM&nbsp;',
                    'PRIVACY POLICY' => 'POLITIQUE DE CONFIDENTIALITÉ',
                    'TERMS & CONDITIONS' => "CONDITIONS D'UTILISATION",
                ),

                'phone_footer' => array(
                    'BLOGGER' => 'BLOGGER',
                    '#LOOKBOOKS' => '#LOOKBOOKS',
                    'HERE' => 'HERE',
                    'Connect With Us' => 'NOUS CONTACTER',
                    'My Account' => 'Mon Compte',
                    'Track Order' => 'Suivi de Commande',
                    'Order History' => 'Mes commandes',
                    'About Us' => 'À propos de nous',
                    'Membership' => 'Adhésion',
                    'Contact Us' => 'Nous contacter',
                    'Copyright © 2006-2016 Choies.com' => 'Copyright © 2006-2016 Choies.com',
                    'Terms & Conditions' => 'Conditions Générales d\'Utilisation',
                    'Privacy Policy' => 'Politique de confidentialité',
                ),
            ),

        ),
        'ru'=>array(
            'lang' => array(
                'quick' =>'Бстрый посмотр',
                'addto' => 'Добавить в избранное',
                'onesize' => 'только один размер',
            ),
			'payment'=> array(
				'choosecard' =>'Пожалуйста, выберите тип карты',
				'choosecard1' =>'Пожалуйста, выберите тип кредитной карты.',
			),

        ),
        
);

