<?php
$payment = array(
    'new' => array(
        'name' => __('New'),
        'description' => __('New Order'),
        'show_to_customer' => TRUE,
        'sendmail' => FALSE,
        'email_template' => NULL,
        'payment' => array( 'success', 'pending', 'failed', 'cancel',
            'partial_paid', 'verify_failed', 'verify_banned', 'verify_pass'
        ),
        'shipment' => NULL,
        'refund' => NULL,
        'bgcolor' => '',
    ),
    'success' => array(
        'name' => __('Success'),
        'description' => __('Success'),
        'show_to_customer' => TRUE,
        'sendmail' => TRUE,
        'email_template' => 'order_payment',
        'payment' => array( 'partial_paid' ),
        'shipment' => array( 'processing', 'partial_shipped', 'shipped', 'delivered' ),
        'refund' => array( 'prepare_refund', 'partial_refund', 'refund' ),
        'bgcolor' => 'lightblue',
    ),
    'pending' => array(
        'name' => __('Pending'),
        'description' => __('Pending'),
        'show_to_customer' => TRUE,
        'sendmail' => FALSE,
        'email_template' => NULL,
        'payment' => array( 'success', 'failed', 'cancel', 'partial_paid',
            'verify_failed', 'verify_banned', 'verify_pass'
        ),
        'shipment' => NULL,
        'refund' => NULL,
        'bgcolor' => '#DDEEFF',
    ),
    'failed' => array(
        'name' => __('Failed'),
        'description' => __('Failed'),
        'show_to_customer' => TRUE,
        'sendmail' => FALSE,
        'email_template' => NULL,
        'payment' => array( 'success', 'pending', 'failed', 'cancel', 'partial_paid',
            'verify_failed', 'verify_banned', 'verify_pass'
        ),
        'shipment' => NULL,
        'refund' => NULL,
        'bgcolor' => '',
    ),
    'cancel' => array(
        'name' => __('Cancel'),
        'description' => __('Cancel'),
        'show_to_customer' => TRUE,
        'sendmail' => FALSE,
        'email_template' => NULL,
        'payment' => NULL,
        'shipment' => NULL,
        'refund' => NULL,
        'bgcolor' => '#DADADA',
    ),
    'partial_paid' => array(
        'name' => __('Partial Paid'),
        'description' => __('Partial Paid'),
        'show_to_customer' => TRUE,
        'sendmail' => FALSE,
        'email_template' => NULL,
        'payment' => array( 'success', 'partial_paid' ),
        'shipment' => array( 'processing', 'partial_shipped', 'shipped', 'delivered' ),
        'refund' => NULL,
        'bgcolor' => '',
    ),
    'verify_failed' => array(
        'name' => __('Failed'),
        'description' => __('Not passed Verification'),
        'show_to_customer' => TRUE,
        'sendmail' => FALSE,
        'email_template' => NULL,
        'payment' => array( 'success', 'pending', 'failed', 'cancel',
            'partial_paid', 'verify_failed', 'verify_banned', 'verify_pass'
        ),
        'shipment' => NULL,
        'refund' => NULL,
        'bgcolor' => '',
    ),
    'verify_banned' => array(
        'name' => __('Failed'),
        'description' => __('Banned List'),
        'show_to_customer' => TRUE,
        'sendmail' => FALSE,
        'email_template' => NULL,
        'payment' => NULL,
        'shipment' => NULL,
        'refund' => NULL,
        'bgcolor' => '',
    ),
    'verify_pass' => array(
        'name' => __('Success'),
        'description' => __('Pay success and pass verification.'),
        'show_to_customer' => TRUE,
        'sendmail' => FALSE,
        'email_template' => NULL,
        'payment' => array( 'partial_paid' ),
        'shipment' => array( 'processing', 'partial_shipped', 'shipped', 'delivered' ),
        'refund' => array( ),
        'bgcolor' => '#00FF00',
    ),
);

$shipment = array(
    'new_s' => array(
        'name' => __('New'),
        'description' => __('New order'),
        'show_to_customer' => TRUE,
        'sendmail' => FALSE,
        'email_template' => NULL,
        'payment' => array( 'success', 'pending', 'failed', 'cancel',
            'partial_paid', 'verify_failed', 'verify_banned', 'verify_pass'
        ),
        'shipment' => array( 'processing', 'partial_shipped', 'shipped', 'delivered' ),
        'refund' => array( 'prepare_refund', 'partial_refund', 'refund' ),
        'bgcolor' => '',
    ),
    'processing' => array(
        'name' => __('Processing'),
        'description' => __('Processing'),
        'show_to_customer' => TRUE,
        'sendmail' => FALSE,
        'email_template' => NULL,
        'payment' => array( 'success', 'pending', 'failed', 'partial_paid',
            'verify_failed', 'verify_banned', 'verify_pass'
        ),
        'shipment' => array( 'processing', 'partial_shipped', 'shipped', 'delivered' ),
        'refund' => array( 'prepare_refund', 'partial_refund', 'refund' ),
        'bgcolor' => '#FFFFBB',
    ),
    'partial_shipped' => array(
        'name' => __('Partial Shipped'),
        'description' => __('Partial Shipped'),
        'show_to_customer' => TRUE,
        'sendmail' => TRUE,
        'email_template' => 'shipping',
        'payment' => array( 'success', 'pending', 'failed', 'partial_paid',
            'verify_failed', 'verify_banned', 'verify_pass'
        ),
        'shipment' => array( 'processing', 'partial_shipped', 'shipped', 'delivered' ),
        'refund' => array( 'prepare_refund', 'partial_refund' ),
        'bgcolor' => 'lightgreen',
    ),
    'shipped' => array(
        'name' => __('Shipped'),
        'description' => __('Shipped'),
        'show_to_customer' => TRUE,
        'sendmail' => TRUE,
        'email_template' => 'shipping',
        'payment' => array( 'success', 'pending', 'failed', 'partial_paid',
            'verify_failed', 'verify_banned', 'verify_pass'
        ),
        'shipment' => array( 'delivered' ),
        'refund' => array( 'prepare_refund', 'partial_refund', 'refund' ),
        'bgcolor' => 'lightgreen',
    ),
    'delivered' => array(
        'name' => __('Delivered'),
        'description' => __('Delivered'),
        'show_to_customer' => TRUE,
        'sendmail' => TRUE,
        'email_template' => 'delivered',
        'payment' => array( 'success', 'pending', 'failed', 'partial_paid',
            'verify_failed', 'verify_banned', 'verify_pass'
        ),
        'shipment' => NULL,
        'refund' => NULL,
        'bgcolor' => '#FFD3D3',
    ),
);

$refund = array(
    'prepare_refund' => array(
        'name' => __('Prepare refund'),
        'description' => __('Prepare refund'),
        'show_to_customer' => TRUE,
        'sendmail' => FALSE,
        'email_template' => NULL,
        'payment' => NULL,
        'shipment' => array( 'processing', 'partial_shipped', 'shipped', 'delivered' ),
        'refund' => array( 'partial_refund', 'refund' ),
        'bgcolor' => '#FFFF00',
    ),
    'partial_refund' => array(
        'name' => __('Partial refund'),
        'description' => __('Partial refund'),
        'show_to_customer' => TRUE,
        'sendmail' => TRUE,
        'email_template' => 'refund',
        'payment' => NULL,
        'shipment' => array( 'processing', 'partial_shipped', 'shipped', 'delivered' ),
        'refund' => array( 'partial_refund', 'refund' ),
        'bgcolor' => '#F0FF00',
    ),
    'refund' => array(
        'name' => __('Refund'),
        'description' => __('Refund'),
        'show_to_customer' => TRUE,
        'sendmail' => TRUE,
        'email_template' => 'refund',
        'payment' => array( 'cancel' ),
        'shipment' => NULL,
        'refund' => NULL,
        'bgcolor' => '#FD3E03',
    )
);

return array(
    'payment' => $payment,
    'shipment' => $shipment,
    'refund' => $refund,
    'return' => array( ),
);