<?php

defined('SYSPATH') or die('No direct script access.');

return array(
    'en' => array(
        'color',
        'material',
        'shop looks',
        'neckline',
        'sleeve length',
        'silhouette',
        'dresses length',
        'pattern type',
        'types',
        'collar',
        'length',
        'style',
        'placket',
        'season',
        'suit type',
        'detail',
        'top',
        'waist type',
        'closure type',
        'fit type',
        'most popular',
    ),
    'de' => array(
        'Farbe',
        'Material',
        'Kauf Blick',
        'Ausschnitt',
        'Ärmellänge',
        'Silhouette',
        'Kleider Länge',
        'Muster Typ',
        'Typen',
        'Kragen',
        'Länge',
        'Stil',
        'Verschluss',
        'Jahreszeit',
        'Anzug Typ',
        'Detail',
        'Top',
        'Bundhöhe',
        'Verschluss Typ',
        'Passend Typ',
        'Am Beliebtesten',
    ),
    'es' => array(
        'Color',
        'Material',
        'Comprar por ocasión',
        'Escote',
        'Longitud de la manga',
        'Silueta',
        'Longitud de Vestido',
        'Tipo de patrón',
        'Tipos',
        'Cuello',
        'Longitud',
        'Estilo',
        'Bolsito',
        'Estación',
        'Tipo de traje',
        'Detalle',
        'Top',
        'Tipo de la cintura',
        'Tipo de cierre',
        'Tipo apto',
        'Lo más popular',
    ),
    'ru' => array(
        'Цвет',
        'материал',
        'Покупать Лук',
        'вырез',
        'длина рукава',
        'силуэт',
        'длина платья',
        'тип рисунки',
        'типы',
        'воротник',
        'длина',
        'стиль',
        'разрез',
        'сезон',
        'тип одежды',
        'детали',
        'топ',
        'тип талии',
        'тип  закрытия',
        'тип подгонки',
        'самые популярные',
    ),
    'pt' => array(
        'color',
        'material',
        'shop looks',
        'neckline',
        'sleeve length',
        'silhouette',
        'dresses length',
        'pattern type',
        'types',
        'collar',
        'length',
        'style',
        'placket',
        'season',
        'suit type',
        'detail',
        'top',
        'waist type',
        'closure type',
        'fit type',
        'most popular',
    ),
    'fr' => array(
        'Couleur',
        'Matériel',
        'Occasion',
        'Encolure',
        'Longueur de manche',
        'Silhouette',
        'Longueur de robe',
        'Type de motif',
        'Types',
        'Col',
        'Longueur',
        'Style',
        'Patte de boutonnage',
        'Saison',
        'Type de suite',
        'Détail',
        'Top',
        'Type de taille',
        'Type de fermeture ',
        'Type de fit',
        'Le plus populaire',
    ),
);