<?php

return array(
    'en' => array(
        'SHOPPING BAG' => 'SHOPPING BAG',
        'We accept' => 'We accept',
        'cart-empty' => array(
            'title1' => 'Your shopping bag is currently empty.',
            'title2' => 'View items already in your.<a href="/customer/wishlist" class="a-underline">wishlist</a>&nbsp;or&nbsp;<a href="/ready-to-be-shipped-c-395" class="a-underline">continue shopping</a>.',
            'title3' => 'There are no items in your shopping bag.',
            'title4' => 'If you have an account with us, please <a href="/customer/login?redirect=/cart/view" class="a-underline">SIGN IN</a> to see items you previously added.',
            ),

        'Your Saved Items' => 'Your Saved Items',
        'NAME' => 'NAME',
        'PRICE' => 'PRICE',
        'OPTION' => 'OPTION',
        'TOTAL' => 'TOTAL',
        'size' => 'Size:',
        'quantity' => 'Quantity:',
        'Item' => 'Item: #',
        'out of stock' => 'out of stock',
        'Delete' => 'Delete',
        'Add To Cart' => 'Add To Cart',
        'js_message1' => 'Are you sure you want to delete this item?',
        'Sale Ends' => 'Sale Ends:',
        'QTY' => 'QTY:',
        'Subtotal' => 'Subtotal:',
        'Continue Shopping' => 'Continue Shopping',

        'Save for Later' => 'Save for Later',
        'message' => "The price and availability of items at Choies are subject to change. The Bag is a temporary place to store a list of your items and reflects each item's most recent price.",
        'message1' => "Shop now! The gift will stay here for only 24 hours!",
        'message2' => "Add 1+ Item Marked \"Free Shipping\" in Your Bag,Enjoy Free Shipping For Your Entire Order",
        'message3' => "Add \"Free Shipping\" item to enjoy free shipping.",
        'message4' => 'of items to enjoy <span>FREE STANDARD SHIPPING</span>',
        'message5' => 'of items to enjoy <span class="red">free</span> standard shipping.',
        'message6' => 'Add "Free Shipping" item to enjoy free shipping.',
        'message7' => '<b class="red">TIP!</b> Just Checkout to Use Your Points & Coupons.',
        'message8' => '<b class="red">TIP!</b> Sign In to Use Your Points & Coupons.',

        'only' => 'only',
        'left' => 'left',

        'Cancel' => 'Cancel',
        'Update' => 'Update',
        'Proceed to checkout' => 'Proceed to checkout',

        'Change Details' => 'Change Details',
        'Special Offers' => 'Special Offers',
        'Take This Offer' => 'Take This Offer',

        'Product Saving' => 'Product Saving:',
        'Cart Saving' => 'Cart Saving:',
        'Add' => 'Add',

        'Guaranteed Secure Checkout' => 'Guaranteed Secure Checkout',
        'Free Worldwide Shipping' => 'Free Worldwide Shipping',
        '60 Day Money Back Warranty' => '60 Day Money Back Warranty',
        'CHOIES Member Sign In' => 'CHOIES Member Sign In',
        'Email address' => 'Email address:',
        'Password' => 'Password:',
        'Forgot password' => 'Forgot password?',
        'Sign in with Facebook' => 'Sign in with Facebook',
        'Sign In' => 'Sign In',

        'CHOIES Member Sign Up' => 'CHOIES Member Sign Up',
        'Confirm password' => 'Confirm password:',
    ),
    'de' => array(
        'SHOPPING BAG' => 'WARENKORB',
        'We accept' => 'Zahlungsmethode',
        'cart-empty' => array(
            'title1' => 'Ihr Warenkorb ist derzeit leer.',
            'title2' => 'Artikel bereits in Ihre.<a href="/customer/wishlist" class="a-underline">Wunschliste</a>&nbsp;oder&nbsp;<a href="/ready-to-be-shipped-c-395" class="a-underline">Einkauf fortsetzen</a>.',
            'title3' => 'Es gibt keine Artikel in Ihrer Einkaufstasche.',
            'title4' => 'Falls Sie ein Konto bei uns haben, bitte <a href="'. LANGPATH.'/customer/login?redirect='.LANGPATH.'/cart/view" class="a-underline">MELDEN SIE SICH AN</a>, um Artikel, die Sie zuvor hinzugefügt hatten, zu sehen.',
        ),

        'Your Saved Items' => 'Ihre Gespeicherte Artikel',
        'NAME' => 'NAME',
        'PRICE' => 'PREIS',
        'OPTION' => 'OPTION',
        'TOTAL' => 'SUMME',
        'size' => 'Größe:',
        'quantity' => 'Menge:',
        'Item' => 'Artikel: #',
        'out of stock' => 'Nicht Auf Lage',
        'Delete' => 'Löschen',
        'Add To Cart' => 'In den Warenkorb',
        'js_message1' => 'Sind Sie sicher, dass Sie diesen Artikel löschen wollen?',
        'Sale Ends' => 'Sale Endet:',
        'QTY' => 'Größe:',
        'Subtotal' => 'Zwischensumme:',
        'Continue Shopping' => 'Weiter Kaufen',

        'Save for Later' => 'Für später Speichern',
        'message' => "Der Preis und die Verfügbarkeit der Artikel auf Choies sind freibleibend. Das Warenkorb ist ein temporärer Ort, um eine Liste der Artikel zu speichern und den jüngsten Preis jedes Element zu spiegeln.",
        'message1' => "Jetzt Kaufen! Das Geschenk wird hier nur 24 Stunden bleiben!",
        'message2' => "1+ Artikel, die als „Free Shipping\" gekennzeichnet sind, in den Warenkorb hinzufügen, Kostenlosen Versand für Ihre gesamte Bestellung Genießen",
        'message3' => "\"Free Shipping\" Artikel in den Einkaufswagen hinzufügen, um kostenlosen Versand zu genießen.",
        'message4' => 'Artikel hinzufügen, um <span>KOSTENLOSEN STANDARDVERSAND </span>',
        'message5' => 'Artikel hinzufügen, um <span class="red">kostenlosen standardversand</span>',
        'message6' => '"Free Shipping" Artikel in den Einkaufswagen hinzufügen, um kostenlosen Versand zu genießen.',
        'message7' => '<b class="red">TIPP!</b> Gerade zur Kasse, um Ihre Punkte & Gutscheine zu verwenden.',
        'message8' => '<b class="red">TIPP!</b> Gerade zur Kasse, um Ihre Punkte & Gutscheine zu verwenden.',

        'only' => 'Nur noch',
        'left' => 'auf Lager',

        'Cancel' => 'Abbrechen',
        'Update' => 'Aktualisieren',
        'Proceed to checkout' => 'ZUR KASSE',

        'Change Details' => 'Details Ändern',
        'Special Offers' => 'Sonderangebote',
        'Take This Offer' => 'Dieses Angebot Nehmen',

        'Product Saving' => 'Product Sparend:',
        'Cart Saving' => 'Warenkorb Sparend:',
        'Add' => 'Noch',

        'Guaranteed Secure Checkout' => 'Garantierter Datenschutz Kasse',
        'Free Worldwide Shipping' => 'Weltweit Versandkostenfrei',
        '60 Day Money Back Warranty' => '60 Tage Geld-Zurück-Garantie',
        'CHOIES Member Sign In' => 'CHOIES Mitglied Anmelden',
        'Email address' => 'Email address:',
        'Password' => 'Passwort:',
        'Forgot password' => 'Forgot password?',
        'Sign in with Facebook' => 'Mit Facebook Verbinden',
        'Sign In' => 'ANMELDEN',

        'CHOIES Member Sign Up' => 'CHOIES Mitglied Registrieren',
        'Confirm password' => 'Passwort Bestätigen:',
    ),
    'es' => array(
        'SHOPPING BAG' => 'MI BOLSA',
        'We accept' => 'Zahlungsmethode',
        'cart-empty' => array(
            'title1' => 'Su cesta de compra está vacía.',
            'title2' => ' Ver artículos que ya están en su <a href="'.LANGPATH.'/customer/wishlist" class="a-underline">Lista de deseos</a>&nbsp;o&nbsp;<a href="'.LANGPATH.'/ready-to-be-shipped-c-395" class="a-underline">Continuar comprando</a>.',
            'title3' => 'No hay artículos en la bolsa de compras.',
            'title4' => ' Si tienes una cuenta con nosotros, por favor <a href="'.LANGPATH.'/customer/login?redirect='.LANGPATH.'/cart/view" class="a-underline">ACCEDE</a> para ver los artículos añadidos anteriormente.',
        ),

        'Your Saved Items' => 'Sus Artículos Guardados',
        'NAME' => 'NOMBRE',
        'PRICE' => 'PRECIO',
        'OPTION' => 'OPCIÓN',
        'TOTAL' => 'TOTAL',
        'size' => 'Größe:',
        'quantity' => 'Menge:',
        'Item' => 'Artículo: #',
        'out of stock' => 'Fuera De Stock',
        'Delete' => 'Eliminar',
        'Add To Cart' => 'Añadir a bolsa',
        'js_message1' => '¿Estás seguro de que quieres borrar esto? No se puede deshacer?',
        'Sale Ends' => 'Fin de Sale:',
        'QTY' => 'Talla:',
        'Subtotal' => 'Subtotal:',
        'Continue Shopping' => 'Seguir comprando',

        'Save for Later' => 'Guardar para después',
        'message' => "El precio y la disponibilidad de los artículos en choies están sujetos a cambios. La Bolsa es un lugar temporal para guardar una lista de sus artículos y refleja el precio más reciente.",
        'message1' => "¡Compre ahora! El regalo solo estará disponible por 24 horas.",
        'message2' => "Añadir 1+ Artículo Marcado “Free Shipping” a Su Bolsa,Disfrutará Envío Gratis por Su Pedido Completo",
        'message3' => "Añadir el artículo marcado con \"Free Shipping\"para disfrutar el envío gratuito.",
        'message4' => 'para disfrutar <span>ENVÍO ESTÁNDAR GRATUITO </span>',
        'message5' => 'para disfrutar <span class="red">envío estándar gratuito</span>',
        'message6' => 'Añadir el artículo marcado con "Free Shipping"para disfrutar el envío gratuito.',
        'message7' => '<b class="red">!CONSEJO!</b> Utilice Sus Puntos Y Cupónes al pagar.',
        'message8' => '<b class="red">!CONSEJO!</b> Registrarse para Usar sus Puntos & Cupones.',

        'only' => 'Sólo queda',
        'left' => '',

        'Cancel' => 'Cancelar',
        'Update' => 'Actualizar',
        'Proceed to checkout' => 'VOY A PAGAR',

        'Change Details' => 'Cambiar Detalles',
        'Special Offers' => 'OFERTAS ESPECIALES',
        'Take This Offer' => 'TOMAR LA OFERTA',

        'Product Saving' => 'Ahorras:',
        'Cart Saving' => 'Carro Ahorra:',
        'Add' => 'Añada los artículos de',

        'Guaranteed Secure Checkout' => 'Pago Seguro Garantizado',
        'Free Worldwide Shipping' => 'Envío Gratis Mundial',
        '60 Day Money Back Warranty' => '60 Días De Rembolso Garantizado',
        'CHOIES Member Sign In' => 'Acceso para socios',
        'Email address' => 'Email:',
        'Password' => 'Contraseña:',
        'Forgot password' => '¿Olvidaste tu contraseña?',
        'Sign in with Facebook' => 'Acceder con Facebook',
        'Sign In' => 'ACCEDER',

        'CHOIES Member Sign Up' => 'Únete a Choies',
        'Confirm password' => 'Confirmar Contraseña:',
    ),
    'fr' => array(
        'SHOPPING BAG' => 'PANIER D’ACHAT',
        'We accept' => 'We accept',
        'cart-empty' => array(
            'title1' => 'Votre panier est vide pour le moment.',
            'title2' => 'Voir les articles déjà dans votre&nbsp;<a href="'.LANGPATH.'/customer/wishlist" class="a-underline">liste d’envies </a>&nbsp;ounbsp;<a href="'.LANGPATH.'/ready-to-be-shipped-c-395" class="a-underline">continuer vos achats.',
            'title3' => 'Il n\'y a pas d\'articles dans votre panier d’achat.',
            'title4' => 'Si vous avez un compte avec nous, <a href="'.LANGPATH.'/customer/login?redirect='. LANGPATH.'/cart/view" class="a-underline">Connectez-vous</a> pour voir les articles que vous avez ajoutés s\'il vous plaît.',
        ),

        'Your Saved Items' => 'Vos Articles Sauvegardés',
        'NAME' => 'NOM',
        'PRICE' => 'PRIX',
        'OPTION' => 'OPTION',
        'TOTAL' => 'SOUS-TOTAL',
        'size' => 'TAILLE:',
        'quantity' => 'Quantité:',
        'Item' => 'Article: #',
        'out of stock' => 'en rupture de stock',
        'Delete' => 'Supprimer',
        'Add To Cart' => 'Ajouter au panier',
        'js_message1' => 'Êtes-vous sûr de vouloir supprimer cet article?',
        'Sale Ends' => 'Promo se termine:',
        'QTY' => 'Quantité:',
        'Subtotal' => 'Sous-total:',
        'Continue Shopping' => 'continuer vos achats',

        'Save for Later' => 'Mettre de côté',
        'message' => "Le prix et la disponibilité des articles sur Choies sont sujettes à changement. Le panier est un endroit temporaire pour stocker une liste de vos articles et refléter prix le plus récent de chaque article.",
        'message1' => "J'en Profite! Le cadeau va rester ici pour 24 heures seulement!",
        'message2' => "Ajoutez 1+ Article Marqué \"Free Shipping\" à Votre Panier,Profitez De La Livraison Gratuite Pour Votre Commande",
        'message3' => "Ajouter \"Free Shipping\" article de profiter de la livraison gratuite",
        'message4' => 'd\'articles pour profiter la <span>LIVRAISON STANDARD GRATUITE </span>',
        'message5' => 'd\'articles pour profiter la <span class="red">livraison standard gratuite</span>.',
        'message6' => 'Ajouter "Free Shipping" article de profiter de la livraison gratuite.',
        'message7' => '<b class="red">TIP!</b> N’oubliez pas d’utiliser vos Points & Coupons.',
        'message8' => '<b class="red">TIP!</b> N’oubliez pas d’utiliser vos Points & Coupons.',


        'only' => 'seulement',
        'left' => 'restants',

        'Cancel' => 'Annuler',
        'Update' => 'Valider',
        'Proceed to checkout' => 'PROCÉDER AU PAIEMENT',

        'Change Details' => 'Modifier',
        'Special Offers' => 'Offres Spéciales',
        'Take This Offer' => 'Prenez Cette Offre',

        'Product Saving' => 'Économise:',
        'Cart Saving' => 'Économie de Panier:',
        'Add' => 'Ajouter',

        'Guaranteed Secure Checkout' => 'Payement En Sécurité',
        'Free Worldwide Shipping' => 'Livraison Internationale Gratuite',
        '60 Day Money Back Warranty' => 'Remboursement Dans Les 60 Jours',
        'CHOIES Member Sign In' => 'Déjà client CHOIES',
        'Email address' => 'Adresse e-mail:',
        'Password' => 'Mot de passe:',
        'Forgot password' => 'Mot de passe oublié?',
        'Sign in with Facebook' => 'Sign in with Facebook',
        'Sign In' => 'Sign In',

        'CHOIES Member Sign Up' => 'Nouveau client CHOIES',
        'Confirm password' => 'Confirmer le mot de passe:',
    ),
);