<?php

return array(
    'en' => array(
        'Place Order' => 'Place Order',
        'Pay' => 'Pay',
        'Succeed' => 'Succeed',
        'COUNTINUE' => 'COUNTINUE',

        'SHIPPING INFORMATION' => 'SHIPPING INFORMATION',
        'Shipping Address' => 'Shipping Address',
        'Edit' => 'Edit',
        'Change' => 'Change',
        'Name' => 'Name:',
        'Tel' => 'Tel:',
        'Address' => 'Address:',

        'Shipping Method' => 'Shipping Method',
        'Add Shipping Insurance for Your Order' => 'Add Shipping Insurance for Your Order',
        'Why get Insurance'=>'Why get Insurance?',
        'title1' => "Shipping Insurance offers superior protection and safety for your valuable items during international delivery. We'll reship your parcel immediately at no extra charge if it's reported lost or damaged.",
        'Default' => 'Default',
        'Set Default' => 'Set Default',
        'Delete' => 'Delete',
        'Add a New Address' => 'Add a New Address',

        'First Name' => 'First Name:',
        'Last Name' => 'Last Name:',
        'Country' => 'Country:',
        'Please choose your country' => 'Please choose your country.',
        'SELECT A COUNTRY' => 'SELECT A COUNTRY',
        'Select One' => 'Select One',

        'City / Town' => 'City / Town',
        'City1' => 'City / Town Name with digits? Please check the accuracy.',
        'Zip / Postal Code' => 'Zip / Postal Code',
        'Code1' => 'It seems that there are no digits in your code, please check the accuracy.',
        'Code2' => 'If there is no zip code in your area, please enter 0000 instead.',
        'Phone' => 'Phone:',
        'Phone1' => 'Please leave correct and complete phone number for accurate delivery by postman',

        'SHIPPING METHODS' => 'SHIPPING METHODS',

        'PAYMENT INFORMATION' => 'PAYMENT INFORMATION',
        'PayPal' => 'PayPal',
        'Credit or Debit Card' => 'Credit or Debit Card',
        'SOFORT' => 'SOFORT',
        'SOFORT BANKING' => 'SOFORT BANKING',
        'IDEAL' => 'IDEAL',
        'iDEAL' => 'iDEAL',

        'COUPON AND POINTS' => 'COUPON AND POINTS',
        'Use Promo Code' => 'Use Promo Code',
        'Code list' => 'Code list',
        'Apply' => 'Apply',
        'Available Codes' => 'Available Codes',
        'No Available Codes' => 'No Available Codes.',
        'Use Choies Points' => 'Use Choies Points',
        '10 Points=$0.1' => '10 Points=$0.1',
        'Redeem' => 'Redeem',
        'points can be used for this time' => 'points can be used for this time.',
        'VIP Policy' => 'VIP Policy',
        'Subtotal' => 'Subtotal',
        'Estimated Shipping' => 'Estimated Shipping',
        'shipping insurance' => 'shipping insurance:',
        'Pay with Coupons & Points' => ' Pay with Coupons & Points:',
        'Wholesale Saving' => 'Wholesale Saving:',
        'Saving' => 'Saving',
        'Total' => 'Total:',
        'Confirm and pay' => 'Confirm and pay',
        'YOUR ORDER SUMMARY' => 'YOUR ORDER SUMMARY',
        'Item' => 'Item: #',
        'Qty' => 'Qty.:',

        'Message' => 'Message',
        '5-100 characters' => '5-100 characters',
        'message_default' => 'Leave any message regarding order placement, product change or delivery options. All messages will be responded within 24 hours.',
        'Submit' => 'Submit',
        'Additional payment security with' => 'Additional payment security with:',
        'Cancel' => 'Cancel',
        'CONFIRM ACTION' => 'CONFIRM ACTION',
        'title2' => 'Are you sure you want to delete this address?',

        'Privileges'=>array(
            'OFF' => 'OFF',
            'title1' => 'Privileges',
            'title2' => 'VIP Level',
            'title3' => 'Accumulated Transaction Amount',
            'title4' => 'Extra Discounts for Items',
            'title5' => 'Points Use Permissions',
            'title6' => 'Order Points Reward',
            'title7' => 'Other Privileges',

            'title8' => 'Non-VIP',
            'title9' => 'You may apply Points equaling up to only 10% of your  order value.',
            'title10' => '$1 = 1 points',
            'title11' => '15% off Coupon Code',
            'title12' => 'Get double shopping points during major holidays.',
            'title13' => 'Special birthday gift.',
            'title14' => 'And More...',
            'title15' => 'Bronze VIP',
            'title16' => 'Silver VIP',
            'title17' => 'Gold VIP',
            'title18' => 'Diamond VIP',
        ),
    ),
    'de' => array(
        'Place Order' => 'Bestellung Aufgeben',
        'Pay' => 'Bezahlen',
        'Succeed' => 'Erfolgreich',
        'COUNTINUE' => 'BESTÄTIGEN',

        'SHIPPING INFORMATION' => 'VERSAND INFORMATIONEN',
        'Shipping Address' => 'Lieferadresse',
        'Edit' => 'Editieren',
        'Change' => 'Wechseln',
        'Name' => 'Name:',
        'Tel' => 'Tel:',
        'Address' => 'Adresse:',

        'Shipping Method' => 'Versandarten',
        'Add Shipping Insurance for Your Order' => 'Versandversicherung für  Ihre Bestellung Hinzufügen',
        'Why get Insurance'=>'Warum Versandversicherung wichtig ist?',
        'title1' => "Versandversicherung schützt Ihre Güter gegen Verlust  und Beschädigung unterwegs. Wir werden Ihr Paket sofort kostenlos erneut versenden, wenn es  verloren oder beschädigt war.",
        'Default' => 'Default',
        'Set Default' => 'Als Default festlegen',
        'Delete' => 'Löschen',
        'Add a New Address' => 'NEUE ADRESSE HINZUFÜGEN',

        'First Name' => 'Vorname:',
        'Last Name' => 'Nachname:',
        'Country' => 'Land:',
        'Please choose your country' => 'Please choose your country.',
        'SELECT A COUNTRY' => 'EIN LAND WÄHLEN',
        'Select One1' => 'Einen Bundesstaat Eingeben',
        'Select One2' => 'Ein(e) Bundesland/Provinz Wählen',

        'City / Town' => 'Stadt / Ort',
        'City1' => 'Stadt / Ort mit Ziffern? Bitte überprüfen Sie es noch einmal.',
        'Zip / Postal Code' => 'PLZ',
        'Code1' => 'Es scheint, dass es keine Ziffern in der PLZ gibt, überprüfen Sie sie bitte erneut.',
        'Code2' => 'Bitte geben Sie Ihre Postleitzahl ein (oder 0000, wenn keine Postleitzahl in Ihrem Land erforderlich ist).',
        'Phone' => 'Telefon:',
        'Phone1' => '',

        'SHIPPING METHODS' => 'VERSANDARTEN',

        'PAYMENT INFORMATION' => 'BEZAHLUNG',
        'PayPal' => 'PayPal',
        'Credit or Debit Card' => 'Kredit- oder Debitkarte',
        'SOFORT' => 'SOFORT',
        'SOFORT BANKING' => 'SOFORT BANKING',
        'IDEAL' => 'IDEAL',
        'iDEAL' => 'iDEAL',

        'COUPON AND POINTS' => 'GUTSCHEINE UND PUNKTE',
        'Use Promo Code' => 'Gutschein Code Verwenden',
        'Code list' => 'Codeliste',
        'Apply' => 'BEWERBEN',
        'Available Codes' => 'VERFÜGBARE CODES',
        'No Available Codes' => 'Keine verfügbaren Codes.',
        'Use Choies Points' => 'Choies Punkte Verwenden',
        '10 Points=$0.1' => '10 Punkte=$0.1',
        'Redeem' => 'EINLÖSEN',
        'points can be used for this time' => 'pPunkte können für diese Zeit verwendet werden.',
        'VIP Policy' => 'VIP Policy',
        'Subtotal' => 'Teilsumme',
        'Estimated Shipping' => 'Verpackung & Versand',
        'shipping insurance' => 'Transportversicherung:',
        'Pay with Coupons & Points' => ' utscheine & Punkte eingelöst:',
        'Wholesale Saving' => 'ARTIKEL Einsparungen:',
        'Saving' => 'Sparend',
        'Total' => 'Gesamtbetrag:',
        'Confirm and pay' => 'Bestätigen und Bezahlen',
        'YOUR ORDER SUMMARY' => ' Ihre Bestellung Details',
        'Item' => 'Artikel: #',
        'Qty' => 'Menge:',

        'Message' => 'Nachricht',
        '5-100 characters' => '5-100 Zeichen',
        'message_default' => 'Hinterlassen Sie jede Nachricht in Bezug auf Bestellungsaufgabe, Änderung des Produkts oder Lieferninformationen. Alle Nachrichten werden innerhalb 24 Stunden antwortet.',
        'Submit' => 'SENDEN',
        'Additional payment security with' => 'Zusätzliche Zahlungssicherheit mit::',
        'Cancel' => 'Abbrechen',
        'CONFIRM ACTION' => 'AKTION BESTÄTIGEN',
        'title2' => 'Sind Sie sicher, dass Sie diese Adresse löschen wollen? Es kann nicht rückgängig gemacht werden.',

        'Privileges'=>array(
            'OFF' => 'Rabatte',
            'title1' => 'Privilegien',
            'title2' => 'VIP Niveau',
            'title3' => 'Kumulierte Transaktionsbetrag',
            'title4' => 'Zusätzliche Rabatte für Artikel',
            'title5' => 'Punkte-Verwenden Berechtigungen',
            'title6' => 'Bestellung-Punkte Belohnung',
            'title7' => 'Andere Vorrechte',

            'title8' => 'Nicht-VIP',
            'title9' => 'Sie können Punkte bis zu insgesamt 10% des Auftragswertes anwenden.',
            'title10' => '$1 = 1 Punkt',
            'title11' => '15% Rabatte Code',
            'title12' => 'Sie können Doppel Einkaufspunkte während der großen Ferien erhalten.',
            'title13' => 'Besondere Geburtstagsgeschenk.',
            'title14' => 'Und mehr...',
            'title15' => 'Bronze VIP',
            'title16' => 'Silber VIP',
            'title17' => 'Gold VIP',
            'title18' => 'Diamant VIP',
        ),
  ),
    'es' => array(
        'Place Order' => 'Realizar Pedido',
        'Pay' => 'Pagar',
        'Succeed' => 'Tener Éxito',
        'COUNTINUE' => 'PRESENTAR',

        'SHIPPING INFORMATION' => 'ENVÍO INFORMACIÓN',
        'Shipping Address' => 'Dirección de Envío ',
        'Edit' => 'Editar',
        'Change' => 'Cambiar',
        'Name' => 'Nombre:',
        'Tel' => 'Tel:',
        'Address' => 'Dirección:',

        'Shipping Method' => 'Método de Envío',
        'Add Shipping Insurance for Your Order' => 'Añade el seguro de envío para su pedido',
        'Why get Insurance'=>'¿Por qué obtener seguros de envío?',
        'title1' => "El seguro de envío ofrece una protección superior y la seguridad para su paquete durante la entrega internacional. Vamos a reenviar su paquete inmediatamente sin coste adicional si se pierde o se rompe.",
        'Default' => 'Dirección',
        'Set Default' => 'Establecer Predeterminada',
        'Delete' => 'Eliminar',
        'Add a New Address' => 'Añadir Una Dirección Nueva',

        'First Name' => 'Primer Nombre:',
        'Last Name' => 'Dirección:',
        'Country' => 'País:',
        'Please choose your country' => 'Please choose your country.',
        'SELECT A COUNTRY' => 'SELECCIONAR UN PAÍS',
        'Select One1' => 'Introduce un Estado',
        'Select One2' => 'Introduce Estado o Provincia',

        'City / Town' => 'Ciudad / Pueblo',
        'City1' => '¿Ciudad / Pueblo con números? Por favor revise la exactitud..',
        'Zip / Postal Code' => 'Código Postal',
        'Code1' => 'Parece que no existen dígitos en el código, por favor revise la exactitud.',
        'Code2' => 'Por favor ingresa 0000, si no se requiere un código postal en tu país.',
        'Phone' => 'Teléfono:',
        'Phone1' => '',

        'SHIPPING METHODS' => 'MÉTODOS DE ENVÍO',

        'PAYMENT INFORMATION' => 'PAGO',
        'PayPal' => 'PayPal',
        'Credit or Debit Card' => 'Tarjeta de Crédito o Débito',
        'SOFORT' => 'SOFORT',
        'SOFORT BANKING' => 'SOFORT BANKING',
        'IDEAL' => 'IDEAL',
        'iDEAL' => 'iDEAL',

        'COUPON AND POINTS' => 'CUPÓNES Y PUNTOS',
        'Use Promo Code' => 'Utilice código de Promoción',
        'Code list' => 'Lista de Código',
        'Apply' => 'Aplicar',
        'Available Codes' => 'Códigos disponibles',
        'No Available Codes' => 'No Códigos Disponibles.',
        'Use Choies Points' => 'Utilice Puntos de Choies',
        '10 Points=$0.1' => '10 Puntos=$0.1',
        'Redeem' => 'Canjear',
        'points can be used for this time' => 'puntos pueden ser utilizados por esta vez.',
        'VIP Policy' => 'VIP Policy',
        'Subtotal' => 'Subtotal:',
        'Estimated Shipping' => 'Coste del Envío:',
        'shipping insurance' => 'Seguros de Envío:',
        'Pay with Coupons & Points' => 'Pagar Con Copónes Y Puntos: ',
        'Wholesale Saving' => 'Wholesale Saving:',
        'Saving' => 'Ahorras',
        'Total' => 'Total:',
        'Confirm and pay' => 'Confirmar y Pagar',
        'YOUR ORDER SUMMARY' => 'SU RESUMEN DE PEDIDO',
        'Item' => 'Artículo: #',
        'Qty' => 'Cantidad:',

        'Message' => 'Mensaje',
        '5-100 characters' => '5-100 caracteres',
        'message_default' => 'Deje cualquier mensaje sobre la realización del pedido, el cambio del producto o la opción de entrega. Todos los mensajes se responderán dentro de las 24 horas.',
        'Submit' => 'PRESENTAR',
        'Additional payment security with' => 'ASeguridad de pago adicional con:',
        'Cancel' => 'Cancelar',
        'CONFIRM ACTION' => 'CONFIRMAR ACCIÓN',
        'title2' => '¿Estás seguro de que quieres borrar esto? No se puede deshacer.',

        'Privileges'=>array(
            'OFF' => 'menos',
            'title1' => 'Privilegios',
            'title2' => 'VIP Nivel',
            'title3' => 'Importe de transacción',
            'title4' => 'Descuento Extra por Articulo de Precio Completo',
            'title5' => 'Puntos Permitidos',
            'title6' => 'Puntos Recompensados de Pedido',
            'title7' => 'Otros Privilegios',

            'title8' => 'NO VIP',
            'title9' => 'Usted puede solicitar puntos que equivalen a sólo 10% de valor del pedido.',
            'title10' => '$1 = 1 Punto',
            'title11' => '15% de descuento  código promocional',
            'title12' => 'Consigue puntos comerciales dobles durante los principales días festivos.',
            'title13' => 'Regalo de cumpleaños especial.',
            'title14' => 'Y más...',
            'title15' => 'VIP Bronce',
            'title16' => 'VIP plata',
            'title17' => 'VIP oro',
            'title18' => 'VIP diamante',
        ),
    ),
    'fr' => array(
        'Place Order' => 'Passer Commande',
        'Pay' => 'Payer',
        'Succeed' => 'Réussir',
        'COUNTINUE' => 'VALIDER',

        'SHIPPING INFORMATION' => 'INFORMATION DE LIVRAISON',
        'Shipping Address' => 'Adresse de livraison',
        'Edit' => 'Rédiger',
        'Change' => 'Changer',
        'Name' => 'NOM:',
        'Tel' => 'Téléphone:',
        'Address' => 'Adresse:',

        'Shipping Method' => 'Mode De Livraison',
        'Add Shipping Insurance for Your Order' => 'Ajouter l’assurance transport pour votre commande',
        'Why get Insurance'=>"Quelle est l'assurance transport?",
        'title1' => "L'assurance transport offre la protection supérieure et la sécurité pour vos articles de valeur pendant la livraison internationale. Nous réexpédierons votre colis immédiatement sans coût supplémentaire s'il est déclaré perdu ou endommagé.",
        'Default' => 'Par Défaut',
        'Set Default' => "régler l'adresse par défaut",
        'Delete' => 'Supprimer',
        'Add a New Address' => 'Ajouter Une Nouvelle Adresse',

        'First Name' => 'Prénom:',
        'Last Name' => 'Nom:',
        'Country' => 'Country:',
        'Please choose your country' => 'Please choose your country.',
        'SELECT A COUNTRY' => 'Sélectionner Un Pays',
        'Select One1' => 'Entrer une Département',
        'Select One2' => 'Entrer une Pays ou Région',

        'City / Town' => 'Ville / Commune',
        'City1' => 'City / Town Name with digits? Please check the accuracy.',
        'Zip / Postal Code' => 'Code postal',
        'Code1' => 'It seems that there are no digits in your code, please check the accuracy.',
        'Code2' => 'Si votre région n\'utilise pas de code postal, veuillez saisir 0000.',
        'Phone' => 'Téléphone:',
        'Phone1' => '',

        'SHIPPING METHODS' => 'MÉTHODES de livraison',

        'PAYMENT INFORMATION' => 'PAIEMENT',
        'PayPal' => 'PayPal',
        'Credit or Debit Card' => 'Carte de Crédit ou Débit',
        'SOFORT' => 'SOFORT',
        'SOFORT BANKING' => 'SOFORT BANKING',
        'IDEAL' => 'IDEAL',
        'iDEAL' => 'iDEAL',

        'COUPON AND POINTS' => 'COUPONS ET POINTS',
        'Use Promo Code' => 'Utilisez le code promo&nbsp;',
        'Code list' => 'Liste De Code',
        'Apply' => 'Appliquer',
        'Available Codes' => 'CODES DISPONIBLES',
        'No Available Codes' => 'Pas De Codes Disponibles.',
        'Use Choies Points' => 'Utilisez Points Choies',
        '10 Points=$0.1' => '10 Points=$0.1',
        'Redeem' => 'Racheter',
        'points can be used for this time' => 'points disponibles pour cette commande.',
        'VIP Policy' => 'VIP Policy',
        'Subtotal' => 'Sous-total:',
        'Estimated Shipping' => 'Livraison',
        'shipping insurance' => 'assurance transport:',
        'Pay with Coupons & Points' => ' COUPONS & POINTS: ',
        'Wholesale Saving' => 'Sale Items Saving:',
        'Saving' => 'Économiser',
        'Total' => 'Total:',
        'Confirm and pay' => 'Confirmer et payer',
        'YOUR ORDER SUMMARY' => 'VÉRIFIEZ VOTRE COMMANDE',
        'Item' => 'Article: #',
        'Qty' => 'Qté.:',

        'Message' => 'Message',
        '5-100 characters' => '5-100 caractères',
        'message_default' => 'Laissez un message concernant le placement de commande, le changement de produit ou les options de livraison. Tous les messages seront répondus dans les 24 heures.',
        'Submit' => 'GARDER',
        'Additional payment security with' => 'Sécurité de paiement supplémentaire avec:',
        'Cancel' => 'annuler',
        'CONFIRM ACTION' => 'CONFIRMATION',
        'title2' => 'Êtes- vous sûr pour le supprimer? Il ne peut pas d’être révoqué.',

        'Privileges'=>array(
            'OFF' => 'de réduction',
            'title1' => 'Privilèges',
            'title2' => 'Niveau VIP',
            'title3' => 'Montant de la transaction accumulée',
            'title4' => 'Les rabais supplémentaires sur articles plein tarif',
            'title5' => 'Permission de l’utilisation des points',
            'title6' => 'Le coût des points',
            'title7' => 'D’autres privilèges',

            'title8' => 'Non-VIP',
            'title9' => 'Vous pouvez utiliser les points équivalant à seulement 10% de la valeur de votre commande.',
            'title10' => '$1 = 1 points',
            'title11' => 'Code de coupon de 15% de réduction',
            'title12' => 'Obtenir des points doubles d\'achat pendant les grandes fêtes.',
            'title13' => 'Les cadeaux d’anniversaire spéciaux,',
            'title14' => 'etc...',
            'title15' => 'VIP Bronze',
            'title16' => 'VIP Argent',
            'title17' => 'VIP Or',
            'title18' => 'VIP Diamant',
        ),
    ),
);